### ISSUE TITLE
Will it be possible to retrieve the data based on tier level from multiple submissions?

### ISSUE THREAD

**Issue by hermidalc** [CBIIT/nci-ctd2-dashboard#143]
_Originally reported by_: @jagus7

**Comment by hermidalc** [comment]
*Original comment by*: @armish

Issue #171 was marked as a duplicate of this issue.

**Comment by hermidalc** [comment]
*Original comment by*: @jagus7


_Thanks, Arman! Sounds good to me.
Sent from iphone

**Comment by hermidalc** [comment]
*Original comment by*: @armish

Unfortunately we don't support that feature right now; but I think this might be a really useful feature to have.
Let's keep this issue open and we can revisit this when we start prioritizing the feature requests for future development.

**Comment by hermidalc** [comment]
*Original comment by*: @jagus7

Arman, That’s correct !  I was just curious to know  whether it is possible or not  for the user  to retrieve for e.g. all the tier 2 data available in Dashboard?
Thank You.
Subhashini

**Comment by hermidalc** [comment]
*Original comment by*: @armish

Hi Subhashini,

Yes, we currently support this via Search or SubjectView. In either of the views, you always get data from multiple submissions for the particular keyword/subject of interest no matter what their tier is -- or am I getting this question wrong?

Let me know.

**Comment by kcs3** [comment]
This can be accomplished by filtering the query after the results are displayed, e.g. entering "Tier 3" in the filter box will show all search results for tier 3 even across different result pages.
Does not warrant further development.
