### ISSUE TITLE
Allow showing search results by Submission

### ISSUE THREAD

**Issue by hermidalc** [CBIIT/nci-ctd2-dashboard#157]
_Originally reported by_: @kcs3

Currently a search returns all matching observations.  There can be hundreds or even thousands of hits.  We could offer an alternative which shows instead which submissions contain hits.  Then the user could examine whichever submission is of most interest for the actual observations matching the search.

**Comment by hermidalc** [comment]
*Original comment by*: @paulclemons

I like this and related ideas, but they seem like major enhancements we should address after we knock off some of the lower-hanging fruit.

**Comment by kcs3** [comment]
This is now being implemented in issue #357.  Since the latest documentation is there, closing this issue.
