### ISSUE TITLE
Sorting Stories  By Date

### ISSUE THREAD

**Issue by hermidalc** [CBIIT/nci-ctd2-dashboard#233]
_Originally reported by_: @jagus7

Currently there is no option available to sort the stories by date.

**Comment by hermidalc** [comment]
*Original comment by*: @vdancik

The dates of stories were updated for the upcoming release.

**Comment by hermidalc** [comment]
*Original comment by*: @jagus7

Received following input for stories:
1. In the "Recent Stories" on the front page, I found most stories are 2-3 years ago. Maybe they can try to rank the stories by publishing dates, so the user can get the latest information.”
2. I think the page should cycle through the recent stories automatically. 
3. I’d prefer the stories and “Navigating and Understanding Dashboard Content” would open a webpage, rather than the popup box. 
4. It would be nice if there was a “Full Story” section when you viewed the observation, instead of having them as two separate items.”

**Comment by hermidalc** [comment]
*Original comment by*: @vdancik


Columbia GBM_MRs 4/6/2014

DFCI YAPYES 6/17/2014

UTSW Discoi 7/8/2014

CSHL FGF19 7/11/2014

Hutch-M Targets 12/12/2014

UCSF-M chemgen 4/13/2015

Hutch-K CTCF 4/12/2015

UCSF-W KRAS 4/8/2015

Stanford Organoids 4/17/2015

UTMDA PIK3R1 4/9/2015

CSHL CDK9 4/17/2015

Columbia PrecMed 4/17/2015

DFCI Function 4/17/2015

T-Gen Eddy 8/6/2015

UTSW NSCLC 7/16/2015

CSHL Brd4 7/15/2015

Columbia AKT-ALL 7/24/2015

UCSF-W NB_splicing 9/9/2015

**Comment by hermidalc** [comment]
*Original comment by*: **donmon**

I can certainly come up with a list of dates, for example when I sent the final, approved html file to Vlado. It won't be different by more than a week or two from what is there now. In the current submissions, the date appears in the path for the files as well as in a box by itself in the spreadsheet, so I need to know from Vlado what to do with the new dates if I generate them.

I personally think oldest first is not necessary. 

Sorting by centers is fine, but the numbers don't demand it yet, especially with the icons easily visible. Looking at all of a center's submissions includes the stories, and they are marked as Story in the description and the details (which is sortable). So I think the sort capability is probably a low priority.

**Comment by hermidalc** [comment]
*Original comment by*: @paulclemons

We need to understand what the dates on the stories should be (when they were written/conceived) rather than simply using the dates that they were included in a submission. Hopefully Don can help with this before he leaves the Network.

**Comment by hermidalc** [comment]
*Original comment by*: @jagus7

It will be helpful to have an option on the date column to sort Oldest to Newest, or  Newest to Oldest.
Sorting stories by Centers is also an useful feature.

**Comment by hermidalc** [comment]
*Original comment by*: **arisfloratos**

It seems that the stories, by default, are listed in chronological order.

What is missing, on the other hand, is the ability to sort by Center.

**Comment by hermidalc** [comment]
*Original comment by*: @vdancik

Stories have a prescribed order and are (almost) sorted by date.

**Comment by kcs3** [comment]
See issue #249 for request for publications by center.

**Comment by kcs3** [comment]
After the complete landing page redesign, only a single story is title is shown, and if "all stories" is clicked, the stories are sorted by date.
