### ISSUE TITLE
Links to CCLE

### ISSUE THREAD

**Issue by hermidalc** [CBIIT/nci-ctd2-dashboard#235]
_Originally reported by_: @jagus7

Cancer Cell Line Encyclopedia (CCLE): current version requires login to view and does not have persistent links

**Comment by hermidalc** [comment]
*Original comment by*: @paulclemons

Agreed, we can't do this right now due to the structure of the CCLE site and URL-space.

**Comment by kcs3** [comment]
Closing because nothing to do.
