### ISSUE TITLE
Links to CTRP Portal

### ISSUE THREAD

**Issue by hermidalc** [CBIIT/nci-ctd2-dashboard#236]
_Originally reported by_: @jagus7

Cancer Therapeutics Response Portal (CTRP): new version will have persistent links (http://www.broadinstitute.org/ctrp.v2.2/?compoundId=362342&compoundName=navitoclax); http://www.broadinstitute.org/ctrp.v2.2/?featureName=CTNNB1); CCLE current version requires login to view and does not have persistent links.

**Comment by hermidalc** [comment]
*Original comment by*: @paulclemons

The CTRP new version will release latest Nov 2. VD - will you prepare URLs from CTRP for background data loads?

**Comment by vdancik** [comment]
This issues is superseded by #364
