### ISSUE TITLE
Link to Drug Bank

### ISSUE THREAD

**Issue by hermidalc** [CBIIT/nci-ctd2-dashboard#237]
_Originally reported by_: @jagus7

Drug Bank: has persistent links (http://www.drugbank.ca/drugs/DB00945)

**Comment by hermidalc** [comment]
*Original comment by*: @paulclemons

Yes, agreed. Vlado, will you be able to make these part of future background data loads for Cpds?

**Comment by hermidalc** [comment]
*Original comment by*: @vdancik

Yes, indeed, that is the intention.

**Comment by hermidalc** [comment]
*Original comment by*: **arisfloratos**

I take it the request here is to add these links to the compound details page, e.g., http://ctd2-dashboard.nci.nih.gov/#subject/463322. Please confirm.

**Comment by vdancik** [comment]
This issues is superseded by #364
