### ISSUE TITLE
Link to COSMIC Database

### ISSUE THREAD

**Issue by hermidalc** [CBIIT/nci-ctd2-dashboard#238]
_Originally reported by_: @jagus7

Catalogue of Somatic Mutations in Cancer (COSMIC-Welcome Trust Sanger Institute): has persistent links (http://www.cancerrxgene.org/translation/Drug/1011, http://www.cancerrxgene.org/translation/CellLine/2878, http://www.cancerrxgene.org/translation/Gene/1036)

**Comment by hermidalc** [comment]
*Original comment by*: @paulclemons

VD - agree with your assessment. Can you attempt a pre-indexing of relationships for CCLs/Cpds?

**Comment by hermidalc** [comment]
*Original comment by*: @vdancik

I propose to pre-compute links for compounds and cell lines as those might need manual curation. Links for genes could be created on the fly.

**Comment by vdancik** [comment]
This issues is superseded by #364
