### ISSUE TITLE
Full gene names

### ISSUE THREAD

**Issue by hermidalc** [CBIIT/nci-ctd2-dashboard#240]
_Originally reported by_: @jagus7

Full names of the genes should be displayed throughout the Dashboard. Use a web service call from HUGO.

HGNC REST info:

http://www.genenames.org/help/rest-web-service-help

e.g. 

http://rest.genenames.org/fetch/symbol/ZNF3

**Comment by hermidalc** [comment]
*Original comment by*: @vdancik

I would say that the full name should be displayed on the gene page, possibly as a title or the first entry in the table below the title. Elsewhere (browse page, observation summary, search page, etc) the symbol should be displayed and the full name should be a hover text.

**Comment by hermidalc** [comment]
*Original comment by*: @kcs3

Should the full gene names be displayed as hover text over the more convenient gene symbols, or displayed outright?

**Comment by hermidalc** [comment]
*Original comment by*: @paulclemons

We should do this throughout the Dashboard.

**Comment by kcs3** [comment]
Should these gene names be retrieved as part of loading the database, rather than while user is interacting with the Dashboard?

**Comment by kcs3** [comment]
On the subject page for each gene, add the following new lines under Gene Symbol.  The data is found in the gene background data file from NCBI (Homo_sapiens.gene_info).

- Gene Name - found in the "description" column.  (Note that the column "Full_name_from_nomenclature_authority" only has names for valid HGNC genes).
- Gene Type -  found in the "type_of_gene" column.

There are other interesting columns we could include:
- "Other_designations", which is the full names of synonyms of this gene (we already have gene symbol synonyms).  This could be included in the existing synonyms field.  For example, for the first gene, A1BG, the additional names are "alpha-1B-glycoprotein|HEL-S-163pA|epididymis secretory sperm binding protein Li 163pA"

- map_location, which is the genomic location

**Comment by kcs3** [comment]
Adding hover text of gene names will be handled as a separate issue.  (see also #292).

**Comment by kcs3** [comment]
Regarding the aliases in the NCBI "Other_designations" column, described above - These extra names are displayed by genecards.org, e.g. 
https://www.genecards.org/cgi-bin/carddisp.pl?gene=A1BG&keywords=A1BG
but on the NCBI gene page, they are only included deep down on the page in section called "General protein information".   However, if you search NCBI gene with "HEL-S-163pA", you do get the A1BG gene page.

**Comment by kcs3** [comment]
Works as expected.  Finds "HEL-S-163pA".

**Comment by kcs3** [comment]
The changes described above in the March 6 comment, and the additional protein name details noted in the comment of July 20, have been tested in production release v4.20.
