### ISSUE TITLE
Feedback from Steering Committee Member

### ISSUE THREAD

**Issue by hermidalc** [CBIIT/nci-ctd2-dashboard#241]
_Originally reported by_: @jagus7

Main issue is utility.  For looking up targets, this is pretty clunky and not comprehensive. I think wiki works better.  For compounds, this is again not comprehensive.  I am not sure tier level is of general utility for someone surveying this. The layout of supporting data is good, but is this better than pubmed if one wants to look for this information. My lab did not find this site particularly useful, and did not feel that this filled a clear unmet need.

**Comment by hermidalc** [comment]
*Original comment by*: @paulclemons

This set of comments is neither constructive nor actionable. Without either property (which Su has solicited) we should ignore.

**Comment by hermidalc** [comment]
*Original comment by*: @jagus7

Contacted the PI and requested to give more specifics and examples.

**Comment by hermidalc** [comment]
*Original comment by*: **arisfloratos**

If this is coming from a CTD2 PI lab, we need to understand better the specific criticisms. What they mean by "chunky" and "not comprehensive"? It would be useful to reach out to the lab and collect some more detail.

**Comment by kcs3** [comment]
No specific improvements mentioned.  Will close.
