### ISSUE TITLE
Tier Definitions

### ISSUE THREAD

**Issue by hermidalc** [CBIIT/nci-ctd2-dashboard#246]
_Originally reported by_: @jagus7

Users suggested the following options
1. Tier definition should be available as a tool-tip or on the sidebar in the details page. 
2. Provide the following brief tier description at the beginning of each of the 3 tabs ("Disease", "Compounds & Perturbagens", "Biomarker, Targets, Genes & Proteins"):

Tier: A CTD^2 Network-defined ranking system for evidence that is based on the extent of characterization associated with a particular study.

```
Tier 1: Preliminary positive observations.
Tier 2: Confirmation of primary results in vitro.
Tier 3: Validation of results in a cancer relevant in vivo model.
```

**Comment by hermidalc** [comment]
*Original comment by*: @jagus7

Received following comment regarding the Tier definitions and assignments:
•  What is Tier 1 ?? Difficult to find the meaning of this terminology. Sometimes labeling is inconsistent. For example, is this observation Tier 3 or Tier 2 (http://ctd2-  
    dashboard.nci.nih.gov/#/observation/1715158)?

**Comment by hermidalc** [comment]
*Original comment by*: @kcs3

The short tier definitions that Paul gives above should appear as hover-text in at least the following pages, just showing the approriate definition for the particular tier indicated, i.e. tier 1, 2 or 3.
1. Submission page has a tier grey oblong after the Title "Submission, e.g. "http://ctd2-dashboard.nci.nih.gov/#submission/1769656"
2. Center page has a table with first column "Tier" grey oblongs, e.g. http://ctd2-dashboard.nci.nih.gov/#center/1441793
3. Observation page has Tier after "Observation" title, but it is not a grey oblong, e.g. http://ctd2-dashboard.nci.nih.gov/#/observation/1769657.   Make that tier a grey oblong also for consistency?

any others?

**Comment by hermidalc** [comment]
*Original comment by*: @paulclemons

Tier 1: Preliminary positive observations.
Tier 2: Confirmation of primary results *in vitro*.
Tier 3: Validation of results in a cancer-relevant *in vivo* model.

(new hyphen and italics)

**Comment by hermidalc** [comment]
*Original comment by*: @vdancik

Issue #170 was marked as a duplicate of this issue.

**Comment by hermidalc** [comment]
*Original comment by*: **jessicamazerik**

There has been discussion with the Steering Committee about publishing the manuscript. Definitely we should link to that when it happens. 

What was the other suggestion? To put a mouse-over bubble with definitions over the "Tier" column in the related observations tables? 

We should close the older issue so we aren't tracking this in 2 places.

**Comment by hermidalc** [comment]
*Original comment by*: @jagus7

Agree, we discussed earlier and hyperlinked to Tier definitions on the Glossary page from the help text on the Browse pages. Looks like users are not able to easily find this information, so we need to consider one of  the above two suggestions to make it more obvious.

**Comment by hermidalc** [comment]
*Original comment by*: @vdancik

This was already discussed in issue #170

**Comment by birrielpc** [comment]
Within the observation tables (i.e. Explore: Biomarkers, Targets; Perturbagens, Candidate Drugs; and Diseases), provide a visualization of arrows to show the progress from Tier 1 to Tier 3. Also, add a link to the tier manuscript (https://www.ncbi.nlm.nih.gov/pubmed/27401613) on these front pages and include a pop-up in the table to explain the Tiers.

**Comment by kcs3** [comment]
Pam added three issues above (July 18, 2018):

1. Within the observation tables (i.e. Explore: Biomarkers, Targets; Perturbagens, Candidate Drugs; and Diseases), provide a visualization of arrows to show the progress from Tier 1 to Tier 3. 
2. Also, add a link to the tier manuscript (https://www.ncbi.nlm.nih.gov/pubmed/27401613) on these front pages and 
3. include a pop-up in the table to explain the Tiers.

Concerning (2), there is now text on the Browse pages that directs the user to an explanation of the tiers, among other things.  This explanatory text is not on other result pages, like the observations page.  Should it be?
Concerning (3), in #433 we address specifics of adding hover text to additional Tiers column headers on various pages.

**Comment by kcs3** [comment]
All concrete issues mentioned above have been dealt with in #433.  
Concerning (2) above, the explanatory text on the browse pages is not need on the simpler observation pages.  These pages do now have an explanation of the Tiers as hover text.

The only issue not dealt with to-date is adding arrows to indicate progress from Tier 1 to 3.  

Closing this issue.
