### ISSUE TITLE
Adding publications on the Centers Page

### ISSUE THREAD

**Issue by hermidalc** [CBIIT/nci-ctd2-dashboard#249]
_Originally reported by_: @jagus7

For some submissions, the number of observations is very high. A directly visible link to the publication(s) corresponding to each submission would be interesting.

**Comment by hermidalc** [comment]
*Original comment by*: @jagus7

Issue #271 was marked as a duplicate of this issue.

**Comment by hermidalc** [comment]
*Original comment by*: @jagus7

Received very similar requests to the one above.
•   Its helpful to have a separate page where the papers are organized by center. Right now, you can only see the publications by clicking on individual stories. 
•  Would be nice for each target to link to Pubmed, or article list supporting its role in cancer. This would make website more of a resource of all available information for each target (or compound, etc), instead of limited to CTD2 experimental work

**Comment by kcs3** [comment]
Note that publications by Center can be queried on the OCG page https://ocg.cancer.gov/programs/ctd2/publications

**Comment by kcs3** [comment]
Now with collapsing of observations, this is no longer needed.
