### ISSUE TITLE
Red-green color not color blind friendly

### ISSUE THREAD

**Issue by hermidalc** [CBIIT/nci-ctd2-dashboard#252]
_Originally reported by_: @jagus7

Most of the links are in red, user was not able to tell the difference

**Comment by hermidalc** [comment]
*Original comment by*: @paulclemons

The different types of color-blindness have different properties. In some cases, R/G look similar, and in others Y/G look similar. Others may know more about this, but avoiding green seems to address both issues.

https://en.wikipedia.org/wiki/Color_blindness#/media/File:Colour_perception_in_different_types_of_colour_blindness.svg

**Comment by hermidalc** [comment]
*Original comment by*: **arisfloratos**

Subhashini, just to clarify, I take it the issue is that people cannot tell apart the links (red color) from the surrounding text (black color). Can you confirm?

You also mention green: is there some other problem involving that color?

**Comment by kcs3** [comment]
I think this refers to the green "+" symbols next to red gene names.  We could try blue.

**Comment by kcs3** [comment]
Color is not conveying any important information here. Will not fix.
