### ISSUE TITLE
Dashboard Promotion

### ISSUE THREAD

**Issue by hermidalc** [CBIIT/nci-ctd2-dashboard#255]
_Originally reported by_: @jagus7
1. Should make a major effort to advertise the resource
2.  Consultant that will work on attracting attention to the website?
   1.  Produce a resource paper + ads/promotional blurbs in journals (Nat. Medicine, Nat. Rev. Drug Discovery, Nat. Rev. Cancer)
3. Rename "dashboard" to something more informative, e.g. "Targets" or some derivative of it.
4. Linking from CTD2 main site
5. Boxes on the right hand side not easy to notice; in a reduced-size browser stacks on the bottom and have to scroll down all the way; could it be moved to the left hand side instead and stack above the rest of the content?
6. No link to Data Portal and Dashboard under "Resources"
7. No immediate/obvious linking from the NIH website

**Comment by hermidalc** [comment]
*Original comment by*: @paulclemons

This issue looks like multiple different issues. Su - can you resolve into multiple issues?
1. does not need to be an issue
2. assign to steering committee (SC)
3. assign to me
4. issue for consideration (probably by SC)
5. assign to Leandro
6. unassigned
7. assign to Ken/Aris
8. assign to Leandro

**Comment by jagus7** [comment]
Majority of these points were addressed.
