### ISSUE TITLE
Use "background" as a role to refer the subjects in the ‘background’ of the stories.

### ISSUE THREAD

**Issue by hermidalc** [CBIIT/nci-ctd2-dashboard#258]
_Originally reported by_: @jagus7

This way the subjects use in stories (when they are used as background) will not be counted for the purposes of ranking the results.

**Comment by hermidalc** [comment]
*Original comment by*: @paulclemons

This issue is important and related to the idea of making the rankings more intuitive and transparent.

**Comment by kcs3** [comment]
This request seems to misuse the role to solve a coding problem.

**Comment by kcs3** [comment]
Let's look at an example:
https://ctd2-dashboard.nci.nih.gov/dashboard/#observation/20190501-broad-ccc-gpx4-0

Three genes have non-background roles, and three have role of background.  But this has nothing to do with the submission being a story, I don't think, it would be this way for any submission.  I am not sure what the desired change or action here is...

**Comment by kcs3** [comment]
This was apparently just a discussion during early implementation of the "background" role.   Nothing needs to be done now.
