### ISSUE TITLE
Use "Research Highlights" instead of "Stories"

### ISSUE THREAD

**Issue by hermidalc** [CBIIT/nci-ctd2-dashboard#259]
_Originally reported by_: **arisfloratos**

This is a matter of personal taste maybe, but it seems to me that using the term "research highlight" is semantically more appropriate/accurate than the term "story" when we take into consideration the target audience of the Dashboard.

**Comment by hermidalc** [comment]
*Original comment by*: @paulclemons

Bring to steering committee (SC) and use whichever they prefer.

**Comment by kcs3** [comment]
Since we have a video out, probably too late to change this now.
