### ISSUE TITLE
Automatic progression if only one observation is not desireable

### ISSUE THREAD

**Issue by hermidalc** [CBIIT/nci-ctd2-dashboard#260]
*Originally reported by*: @kcs3

An early feature of the Dashboard was that if there is only one observation on a result page, the observation page is automatically opened.  (I think this is the right relationship...)

This has the unfortunate effect of only showing the Submission page for a few seconds.  The submission page has interesting information, such as the "Similar Submissions" table.  Even if you go back to this Submission page, after a few seconds it will return you to the Observation page.

One can see this by searching for "ovarian cancer" (this is from Don Monroe's example in issue #188).  At the bottom of the page, you will see a single submission, for PAX8 from Dana Farber.  If you click on "1 observation" you will be taken to the Submissions page but then on the the Observation page.

I suggest we just remove this particular feature as it causes confusion and is an unexpected behavior.

**Comment by hermidalc** [comment]
*Original comment by*: **arisfloratos**

I agree as well, I too found the automatic redirection unexpected and unwanted...

**Comment by hermidalc** [comment]
*Original comment by*: @vdancik

We need to distinguish between stories and non-story submissions. While redirection is not desired for non-stories, it is desired for stories where we don't want users to go through three unintuitive clicks to read the story. Automatic redirection was an attempt to get to written stories more directly - I agree that we should revisit how to achieve that in a more efficient manner.

**Comment by kcs3** [comment]
The code to add this skip adds a lot of complexity to do something not right.  Rather than make things worse by trying to only trigger it for stories, perhaps stories can be treated in a different way altogether?  But I would like to get rid of this code first.
