### ISSUE TITLE
Dashboard promotion 2

### ISSUE THREAD

**Issue by hermidalc** [CBIIT/nci-ctd2-dashboard#261]
_Originally reported by_: @jagus7

1.Linking from CTD2 main site
2.Boxes on the right hand side not easy to notice; in a reduced-size browser stacks on the bottom and have to scroll down all the way; could it be moved to the left hand side instead and stack above the rest of the content?
3.No link to Data Portal and Dashboard under "Resources"
4.No immediate/obvious linking from the NIH website

**Comment by hermidalc** [comment]
*Original comment by*: **jessicamazerik**

We added a link to the Dashboard that appears in the mobile version of all the CTD^2 pages on OCG's site: https://ocg.cancer.gov/programs/ctd2.

More on the other issues soon...

**Comment by kcs3** [comment]
Overlaps with #255

**Comment by jagus7** [comment]
This is a duplicate of Issue #255.
