### ISSUE TITLE
Downloadability

### ISSUE THREAD

**Issue by hermidalc** [CBIIT/nci-ctd2-dashboard#264]
_Originally reported by_: @jagus7

would like to download a table/tsv/csv file from here:
http://ctd2-dashboard.nci.nih.gov/#explore/compound/Perturbagen,Candidate%20Drug
http://ctd2-dashboard.nci.nih.gov/#subject/463322

Paul's Comment: In terms of "getting all compounds" as a download, it's not really the scope of Dashboard, but we could provide something like this in Resources. I don't think it's reasonable that users can get a custom download, but it should be straightforward for them to "get all".

Subhashini: This request also came during the F2F meeting. Leandro and Arman said this is out of scope and cant be done in an easy way.  Users request is basically to download evidence on a gene/compound  of interest from multiple submissions and this will require to combine multiple observation tables/files into a single file, which is relatively complicated/hard.

**Comment by kcs3** [comment]
Related to #254
