### ISSUE TITLE
Short descriptions for roles and subjects, for user consumption.

### ISSUE THREAD

**Issue by hermidalc** [CBIIT/nci-ctd2-dashboard#266]
_Originally reported by_: **arisfloratos**

We need a short description for each subject type and for each role. These will be used as context-specific help, to explain to Dashboard users what each subject/role represents (e.g., when  users customize roles in Browse pages; or when picking subjects/roles in the template helper).

**Comment by kcs3** [comment]
Enhanced tool-tips have been handled in other issues now.
