### ISSUE TITLE
Provide Links to the Primary Data

### ISSUE THREAD

**Issue by hermidalc** [CBIIT/nci-ctd2-dashboard#270]
_Originally reported by_: @jagus7

Once the primary data supporting Dashboard entries is publically available, it would be useful to have links from individual items taken from that data back to the original data files. These might be in a public database, like GEO, might be on a Center website, or might be deposited with the CTD2. The idea is to make it easy to download an entire screen for independent analysis rather than make an investigator search around the web.

**Comment by hermidalc** [comment]
*Original comment by*: @jagus7

We are providing links to CTD^2 Data Portal, but not to GEO submissions or Center's website in the evidence table. I think the links to Data Portal should be more obvious. We can discuss during our monthly teleconference.

**Comment by kcs3** [comment]
Submissions are usually made at the time of publication, and there is no reason that submitters cannot include a link to GEO in their evidence if this is warranted.  This is perhaps another issue for a style guide.
