### ISSUE TITLE
Organizing Observations with Visuals

### ISSUE THREAD

**Issue by hermidalc** [CBIIT/nci-ctd2-dashboard#273]
_Originally reported by_: @jagus7

The CTD2 website has pretty impressive data. One thing I believe could be helpful is how UCSF has organized its observations with a figure and reference at the end as evidence for each of the claims made. Having such a representation for each of the biomarker would be more useful to the reader (similar to cbioportal in terms of ease of visualization).

**Comment by kcs3** [comment]
This is an issue for submitters.  I think many submssions already contain figures and references but we can emphasize their inclusion in guidelines to submitters.  Do we want to develop a style guide for submitters?
