### ISSUE TITLE
Evidence table hover text request

### ISSUE THREAD

**Issue by hermidalc** [CBIIT/nci-ctd2-dashboard#276]
_Originally reported by_: @kcs3

This is an offshot of issue #227.

A comment in "CTD^2 Dashboard-Columbia Action Items.docx" item 6 requests the following:

The following sentence should be placed as hover text over the "Type" header in the observation Evidence tables:  "Examples include the following: literature, measured, link, reference, background, observed, computed, written, resources, and species".

**Comment by kcs3** [comment]
I am not sure this helps unless some additional context is added.
