### ISSUE TITLE
Priortization of Subjects by People's Choice

### ISSUE THREAD

**Issue by hermidalc** [CBIIT/nci-ctd2-dashboard#277]
_Originally reported by_: @jagus7

It will be nice as the site grows to have some sort of "popular" or voting option within each gene/drug's page of results so that the most "important" results are at the top.  I know Tier 3 is at the top generally, and that's ok, but perhaps other important but lower Tier results could be prioritized to be on the front page of each drug/gene's pages based on how important users have found it rather than the current ranking scheme.  Again, I don't think this makes a big difference right now, but if there were to be 100X the amount of results on the Dashboard someday compared to right now, then something like this would perhaps help users out (though it might also promote group thinking...).

**Comment by kcs3** [comment]
The database is read-only; we do not intend to support user-generated feedback.
