### ISSUE TITLE
Additional changes to CTD2 logo (continues #226)

### ISSUE THREAD

**Issue by hermidalc** [CBIIT/nci-ctd2-dashboard#278]
_Originally reported by_: @kcs3

Suhashini made the following request, which is copied from issue #226:

The new CTD^2 Data Portal clickable image would benefit from having the following text associated with it (either above or below): "Access the CTD^2 Data Portal.” Also, to improve contrast, can the image be outlined in dark red to match the other red on the pages, or can a red box be created behind the image to make it stand out?

**Comment by hermidalc** [comment]
*Original comment by*: @jagus7

Please also the text below:
Click on the icon to access raw/analyzed data of CTD^2 Network.

**Comment by kcs3** [comment]
The data portal image is going away, to be replaced by a tutorial or similar.
