### ISSUE TITLE
Remove Spaces in URLs of the Project Pages

### ISSUE THREAD

**Issue by hermidalc** [CBIIT/nci-ctd2-dashboard#281]
_Originally reported by_: @jagus7

Please remove spaces in the URLs of the project pages. 
Example:
http://ctd2-dashboard.nci.nih.gov/#center/1441870/Validating%20ROS%20as%20a%20therapeutic%20target%20in%20intra-hepatic%20cholangiocarcinoma

**Comment by kcs3** [comment]
This problem will be solved in #317, stable links
