### ISSUE TITLE
Automated content submission

### ISSUE THREAD

**Issue by hermidalc** [CBIIT/nci-ctd2-dashboard#282]
_Originally reported by_: @vdancik

We aim to automate and enhance creation of new Dashboard submissions. As a prototype template-generator already exists in the Dashboard code base, we propose that Columbia will lead this software development effort with Broad, as data stewards, playing a key design/requirements role. Collectively, the teams will start by evaluating the suitability and shortcomings of the existing tool to generate an initial set of requirements. The Centers will work together to extend the current template preview to a usable submission-review system. In addition, Broad and Columbia will work together to define tools and processes for curating roles and subject CVs within the Dashboard framework

**Comment by hermidalc** [comment]
*Original comment by*: @vdancik

Issue #105 was marked as a duplicate of this issue.

**Comment by hermidalc** [comment]
*Original comment by*: @vdancik

Issue #131 was marked as a duplicate of this issue.

**Comment by hermidalc** [comment]
*Original comment by*: @vdancik

Issue #110 was marked as a duplicate of this issue.

**Comment by hermidalc** [comment]
*Original comment by*: @vdancik

Issue #109 was marked as a duplicate of this issue.

**Comment by hermidalc** [comment]
*Original comment by*: @vdancik

Issue #108 was marked as a duplicate of this issue.

**Comment by hermidalc** [comment]
*Original comment by*: @vdancik

Issue #107 was marked as a duplicate of this issue.

**Comment by hermidalc** [comment]
*Original comment by*: @vdancik

Issue #106 was marked as a duplicate of this issue.

**Comment by hermidalc** [comment]
*Original comment by*: @vdancik

Issue #104 was marked as a duplicate of this issue.

**Comment by hermidalc** [comment]
*Original comment by*: @vdancik

Issue #103 was marked as a duplicate of this issue.

**Comment by kcs3** [comment]
This actually now belongs in the Submission Builder github.

**Comment by kcs3** [comment]
All of the duplicate issues mentioned above were previously closed in favor of this issue.  This issue has been addressed in formal design requirement documents for the Submission Builder project.
Closing this issue.
