### ISSUE TITLE
Support for HTML files

### ISSUE THREAD

**Issue by hermidalc** [CBIIT/nci-ctd2-dashboard#286]
_Originally reported by_: @vdancik

Right now all HTML files are considered to be stories and are shown as a pop-up on top of the observation page. Some submissions may contain HTML files and consider them drill-down pages, i.e. they should be shown as a page in a new tab rather then as a pop-up. 

We should design and implement a mechanism for submissions to indicate how to treat HTML files.

**Comment by hermidalc** [comment]
*Original comment by*: @vdancik

This was motivated by issue #280

**Comment by kcs3** [comment]
No test case at this time.  There was previously such a file but it is now handled by URL reference to site outside of Dashboard.

Closing for now, will watch for submissions that might include this in future.
