### ISSUE TITLE
Link from story not working

### ISSUE THREAD

**Issue by vdancik** [CBIIT/nci-ctd2-dashboard#287]
A link for CCL5 in the HTML file of the DFCI story "Discovery and validation of TBK1 as a target in KRAS-dependent lung cancers" does not work. The remaining links in the HTML file appear to be working and CCL5 link on the observation page works as well.

**Comment by vdancik** [comment]
Emory story "Sensing Interactions Between Proteins in Cancer Cells" has the same issue. Only appears to affect stories that have ten or more genes and only genes 10+ are affected.

**Comment by kcs3** [comment]
From Vlado: 
1. Only appears to affect stories that have ten or more genes and only genes 10+ are affected.
2. Emory story "Sensing Interactions Between Proteins in Cancer Cells" has the same issue. 
3. "Discovery of structurally redundant essential relationships in the SWI/SNF complex in cancer" is another story with the symptom, this time "tissue_sample_10" link fails and "tissue_sample_1" to "tissue_sample_9" links work.

**Comment by kcs3** [comment]
Tested in production.  Closing issue.
