### ISSUE TITLE
Center submissions table details never load on page 2 or greater

### ISSUE THREAD

**Issue by hermidalc** [CBIIT/nci-ctd2-dashboard#288]
This is a regression because I believe this used to work. 

Example:
http://ctd2-dashboard.nci.nih.gov/#center/1441870
Go to page 2
Details column always shows "loading..."

Not sure if this regression goes beyond the center submissions table page and might be a general bug related to asynchronous loading on page 2 or greater of any table.

**Comment by zhouji2013** [comment]
After analyzing the code and testing the version of last August, I believe it has always been like this. I agree it is hard to think that we never noticed, but the asynchronous update of the currently invisible pages basically would not work in the present design. To avoid major back-end change or over-complicate the code, I fixed this by changing the update of 'details' column to be synchronous.

**Comment by zhouji2013** [comment]
CenterListView will have the same issue. It does not happen only because the page size is set to be 25 intentionally while the current number of the centers is fewer than 25. The default page size is 10.
