### ISSUE TITLE
Make PrePPI default interactome database; accompany with explanation and PDF of descriptions of other interactive databases

### ISSUE THREAD

**Issue by mazerikjn** [CBIIT/nci-ctd2-dashboard#290]
On the “Cellular Network Knowledge Base” page, PrePPI will be made the default interactome database. It will be accompanied with a 2-3 sentence explanation as to why it is the default (i.e., it is good for general use and a good starting point because it is the most comprehensive interactive dataset). Each interactome database is currently associated with a short description that only appears when a user clicks on that interactome database’s name. These descriptions will be compiled into a single PDF and the PDF will be posted.

**Comment by kcs3** [comment]
Zhou could you move Preppi to the top of the list and select it by default.  I will provide the requested text separately.

**Comment by kcs3** [comment]
Waiting for new interaction database descriptions.

**Comment by kcs3** [comment]
Improved descriptions for each option were implemented in the user interface in #453.
