### ISSUE TITLE
Browse bars on front page

### ISSUE THREAD

**Issue by vdancik** [CBIIT/nci-ctd2-dashboard#291]
The colored bars on the front page that contain  Browse buttons are not aligned with the rest of the page and are shifted to the left.

![image](https://cloud.githubusercontent.com/assets/15987932/17181258/70eab89a-53ed-11e6-901e-172982d4ac9b.png)

**Comment by hermidalc** [comment]
Apologies didn't see this, I've made a new ticket along with another layout fix #309 and will close this issue.
