### ISSUE TITLE
Add LINCS to Resources menu

### ISSUE THREAD

**Issue by kcs3** [CBIIT/nci-ctd2-dashboard#293]
There is a request to add a link to LINCS to the top level Resources menu.

Please evaluate if it is reasonable to make the menu hierarchical.  There would be an entry "Outside Resources" in the main menu and this item would lead to a submenu.  The submenu at this time would only have "LINCS" in it but other outside resources could be added later.

The main LINCS URL is "http://www.lincsproject.org/"

**Comment by zhouji2013** [comment]
done
