### ISSUE TITLE
Edit to text in yellow boxes on tops of "Browse" pages

### ISSUE THREAD

**Issue by mazerikjn** [CBIIT/nci-ctd2-dashboard#299]
please update text to read (new text is **BOLD**):
Entries listed below are ordered by relevance, based on the number of Centers providing observations and Tier evidence level (must be at least Tier 2). **For each Center, only its highest Tier of evidence counts toward the score.** Currently displaying observations involving Biomarkers, Targets, Genes & Proteins (genes) that have been assigned one of the following roles: Biomarker, Target (see background information for the meaning of observations, roles, and Tiers).

**Comment by paulclemons** [comment]
I think Tier 2 is required to be in the list, but Tier 1 data (for those in
the list) counts toward the score. If true, then, we should say the first
sentence a little differently as well (suggesting remove red statement; use
green statement instead).

Entries listed below are ordered by relevance, based on the number of
Centers providing observations and Tier evidence level *(must be at least
Tier 2)*. *For each Center, only its highest Tier of evidence counts toward
the score.* *Entries must have Tier 2 evidence or higher to be in the
list.* Currently
displaying observations involving Biomarkers, Targets, Genes & Proteins
(genes) that have been assigned one of the following roles: Biomarker,
Target (see background information for the meaning of observations, roles,
and Tiers).

________________________
Paul Clemons
pclemons@broadinstitute.org
(617) 714-7346 - office
(617) 359-9092 - cell
________________________

**Comment by zhouji2013** [comment]
The red statement and green statement Paul refers to do not show up with color. Can we have a finalized version of this text?

**Comment by paulclemons** [comment]
[image: Inline image 1]

________________________
Paul Clemons
pclemons@broadinstitute.org
(617) 714-7346 - office
(617) 359-9092 - cell
________________________

**Comment by zhouji2013** [comment]
I still cannot see the image you tried to attach. As I understand, the text should read as following (please confirm):

Entries listed below are ordered by relevance, based on the number of Centers providing observations and Tier evidence level. For each Center, only its highest Tier of evidence counts toward the score. Entries must have Tier 2 evidence or higher to be in the list. Currently displaying observations involving Biomarkers, Targets, Genes & Proteins (genes) that have been assigned one of the following roles: Biomarker, Target (see background information for the meaning of observations, roles, and Tiers).

**Comment by paulclemons** [comment]
looks good

________________________
Paul Clemons
pclemons@broadinstitute.org
(617) 714-7346 - office
(617) 359-9092 - cell
________________________
