### ISSUE TITLE
Edit the description on the Dashboard landing page

### ISSUE THREAD

**Issue by jagus7** [CBIIT/nci-ctd2-dashboard#301]

**Comment by jagus7** [comment]
Please replace the current text on the landing page with the attached text.
[Dashboard Landing Page Text-Revised.docx](https://github.com/CBIIT/nci-ctd2-dashboard/files/420168/Dashboard.Landing.Page.Text-Revised.docx)

**Comment by paulclemons** [comment]
I'm happy with this text.
