### ISSUE TITLE
Highlight the active page with a different color in the browse bar

### ISSUE THREAD

**Issue by jagus7** [CBIIT/nci-ctd2-dashboard#302]
A.	Currently the active page is highlighted with white letters on the navigation bar and other navigation items are faded. To have other items also displayed clearly, highlight the active page with a different color and have the rest of the items in white color.

**Comment by jagus7** [comment]
Currently the active page is highlighted with white letters on the navigation bar and other navigation items are faded. To have other items also displayed clearly, highlight the active page with a different color and have the rest of the items in white color.

**Comment by hermidalc** [comment]
The fix made was not exactly what OCG wanted, assigned to myself and will complete issue.
