### ISSUE TITLE
Default entries list of "Browse pages" should be changed

### ISSUE THREAD

**Issue by jagus7** [CBIIT/nci-ctd2-dashboard#304]
On the diseases page, the list should be alphabetized. All items in the list should also be shown by default if the list contains less than 100 items.

**Comment by kcs3** [comment]
If the page being refered to is
https://ctd2-dashboard.nci.nih.gov/dashboard/#explore/context/Disease
then this entries are ordered by their significance score.  They can be sorted alphabetically by clicking on the "Name" column header.

I suggest no change here.
