### ISSUE TITLE
Date sorting doesn't work properly on each Center page

### ISSUE THREAD

**Issue by hermidalc** [CBIIT/nci-ctd2-dashboard#308]
It just doesn't seem to work at all when you try to sort ascending or descending.

**Comment by kcs3** [comment]
This issue refers to going to the page for an individual center, listing its projects and observations.  

Resorting by date is not implemented.  Note that if it were, it would require reworking the already very confusing listing of projects by tier.  It is the observations that have dates, but projects are currently higher in the sort order (Tier - Project - Observation by date).    Sorting by date would invert this and may be too confusing

**Comment by kcs3** [comment]
We should see if we can do this.

**Comment by kcs3** [comment]
The above note from July 31, 2017 is not correct.  We are able to properly associate submissions with projects when sorted by Tier, Description and Details columns.  So we should be able to sort by Date also if we can properly interpret the date itself.

https://ctd2-dashboard.nci.nih.gov/dashboard/#center/columbia

Please implement sorting by Date in the Centers/submissions table.

**Comment by kcs3** [comment]
Tested on local instance.  The behavior is as follows.  When sorting by Date, the project with the earliest submission is listed first, and all of its remaining submissions are then ordered by date within the same project block.  Then the project with the next-earliest submission is shown, with all of its submissions then in date order.  And so forth for all projects.  Nice!

**Comment by kcs3** [comment]
Tested on production release v3.40.  See note above for the exact behavior implemented.
