### ISSUE TITLE
Pop-up text on subject pages to source metadata

### ISSUE THREAD

**Issue by paulclemons** [CBIIT/nci-ctd2-dashboard#312]
For example, when you mouse over "Gene symbol" it would say "from HGNC", or when you mouse over "Synonyms/related terms" it would say "from Entrez"

**Comment by hermidalc** [comment]
Hi Paul - would you prefer that I add a footnote within each cell in a smaller font mentioning the source so that they can see it without needing to hover over?

**Comment by paulclemons** [comment]
that could be fine, too. this came about from a conversation I had with
Daniela yesterday, so maybe see which one she prefers


________________________
Paul Clemons
pclemons@broadinstitute.org
(617) 714-7346 - office
(617) 359-9092 - cell
________________________

**Comment by hermidalc** [comment]
Thanks, I’ll ask her and Subhashini
