### ISSUE TITLE
Redesign of the landing page

### ISSUE THREAD

**Issue by jagus7** [CBIIT/nci-ctd2-dashboard#313]
1. To attract more users, it will be good to feature data submissions along with the stories on the landing page. Hence, “Recent stories” should be replaced with “Recent Submissions” and include recent data and story submissions. In case of submissions/projects having more than one observation, submitting Centers will pick the observations to be displayed on the landing page.
2. To make the Browse options prominent all three Browse columns will be moved next to the content and then will display the “Recent Submissions” on the landing page.

**Comment by birrielpc** [comment]
1. Revise landing page text to a concise summary and emphasize what is unique about the Dashboard (e.g. synthesizes data from x no. of Centers about a Subject) [see attachment below]
2. Incorporate pictures and buttons for browsing [see attachment below]
3. Embed tutorial videos on the page instead of opening as a pop-up window
4. A teaser video that summarizes the Dashboard functionalities will be included in the top right hand corner

Refer to the PowerPoint attachment for a revised visual layout of the landing page:
[CTD^2_DB_LandingPage_Layout.pptx](https://github.com/CBIIT/nci-ctd2-dashboard/files/2206270/CTD.2_DB_LandingPage_Layout.pptx)

Refer to the Word document for specifics on edits needed to be made on the landing page:
[CTD^2_Dashboard_Edits_Landing_Page.docx](https://github.com/CBIIT/nci-ctd2-dashboard/files/2206277/CTD.2_Dashboard_Edits_Landing_Page.docx)

**Comment by jagus7** [comment]
Revised layout for the Dashboard landing page

**Comment by jagus7** [comment]
[CTD^2_DB_LandingPage_Layout_Revised_v1.pptx](https://github.com/CBIIT/nci-ctd2-dashboard/files/2530925/CTD.2_DB_LandingPage_Layout_Revised_v1.pptx)

**Comment by jagus7** [comment]
[CTD^2_DB_LandingPage_Layout_Revised_v2.pptx](https://github.com/CBIIT/nci-ctd2-dashboard/files/2626270/CTD.2_DB_LandingPage_Layout_Revised_v2.pptx)
Please use this attached new layout!

**Comment by jagus7** [comment]
1. https://ocg.cancer.gov/dashboard-export.xml; this "xml" link could be used to pull the content from the OCG’s Drupal site to the Dashboard landing page.
2. Update to the "Footer" section; details are included in the attached word document.
[Dashboard_Footer_Text.docx](https://github.com/CBIIT/nci-ctd2-dashboard/files/2634835/Dashboard_Footer_Text.docx)

**Comment by jagus7** [comment]
•	The team felt that new layout is dull-looking, to improve the look and feel of the site some suggestions were made:
o	Reduce CTD2 logo size, move bullets to the left, align the video icons with the text. 
o	Attributions in the footer section are not prominent, they appear only after users click the button. It may not be obvious for users to cite the site; one suggestion was to add “How to Cite” under the resources menu.
o	Browse options are not obvious so suggested to use “Big Button” like the one showed below: 
![image](https://user-images.githubusercontent.com/17437681/52135137-1fb99180-2613-11e9-9412-d4b0147e6865.png)

 Subhashini will work on the color schema of the navigation menu and send template to Dashboard team for feedback.

**Comment by jagus7** [comment]
![image](https://user-images.githubusercontent.com/17437681/52501560-9aa02080-2bae-11e9-969a-aca87201771f.png)

**Comment by jagus7** [comment]
Attached new layout and color schema for the Dashboard landing page.

[Dashboard-Button_Mockup_Updated_v4.pptx](https://github.com/CBIIT/nci-ctd2-dashboard/files/2920702/Dashboard-Button_Mockup_Updated_v4.pptx)

Please include the link "https://ocg.cancer.gov/programs/ctd2/ctd2-publication-guidelines" for publication guideliens and include the text in listed in the pop-up window of Glossary (currently lised in the footer)

**Comment by kcs3** [comment]
Well after all that the landing page has been reduced to almost nothing...for now.

**Comment by jagus7** [comment]
1.  Pull-down menu for "CTD2 Dashboard" should include Glossary and Publication guidelines as indicated in the above slide. 
2.  Hover-over text on browse buttons should be for 
a. Genes and Proteins: Find experimental evidence for cancer targets that are implicated in a cancer model
b. Compounds and perturbagens: Find experimental evidence for agents that show activity in a cancer model
C. Disease Context: Find disease-specific targets or agents

**Comment by zhouji2013** [comment]
> 
> 
>     1. Pull-down menu for "CTD2 Dashboard" should include Glossary and Publication guidelines as indicated in the above slide.
> 
>     2. Hover-over text on browse buttons should be for
>        a. Genes and Proteins: Find experimental evidence for cancer targets that are implicated in a cancer model
>        b. Compounds and perturbagens: Find experimental evidence for agents that show activity in a cancer model
>        C. Disease Context: Find disease-specific targets or agents

Glossary is to be put into the Resources dropdown menu, after Publications, per Ken's recommendation, instead of changing the 'homepage' link.

**Comment by kcs3** [comment]
OK these new issues are confirmed implemented in production release 3.30.
