### ISSUE TITLE
Add breadcrumbs to help navigate users back to the starting point

### ISSUE THREAD

**Issue by jagus7** [CBIIT/nci-ctd2-dashboard#314]
Currently it takes at least 3-4 clicks to go to an evidence page. It also takes users away from the page where they started and makes it harder to go back. Hence, it was suggested to add breadcrumbs to help navigate users back to the starting point.

**Comment by kcs3** [comment]
The Dashboard is not arranged in a hierarchical fashion - most everything is on separate but parallel levels, e.g. subjects, observations, submissions.  The Dashboard facilitates clicking around in this web of connections.  For example:

https://ctd2-dashboard.nci.nih.gov/dashboard/#submission/1703190

https://ctd2-dashboard.nci.nih.gov/dashboard/#/observation/1703191

https://ctd2-dashboard.nci.nih.gov/dashboard/#/subject/465532

So it is not clear that the breadcrumbs would really work out....

**Comment by kcs3** [comment]
Not a good fit to Dashboard use.
