### ISSUE TITLE
Build additional general search box

### ISSUE THREAD

**Issue by jagus7** [CBIIT/nci-ctd2-dashboard#315]
Currently, users can only search with the terms hot-linked (inter-connected) in the Dashboard. Also, submitters have to spend a lot of time recasting the observation summaries to use as many of the column tags as possible, so those terms would appear in search results. Hence, it will be useful to have an additional search engine where users can search things by default.

**Comment by kcs3** [comment]
Apparently the Dashboard uses an outdated version of Lucene to manage search.  We should investigate what could be gained by moving to a current version and properly configuring it.

**Comment by kcs3** [comment]
It turns out that terms do not have to be included in the "Observations Summaries" to be found by a search.  This was an urban legend.

**Comment by kcs3** [comment]
A number of new issues dealing with search now supersede this issue, the most important being #343, but including also #351, #353, and #356.

Closing this issue.
