### ISSUE TITLE
Link to project page from submission/observation pages

### ISSUE THREAD

**Issue by vdancik** [CBIIT/nci-ctd2-dashboard#316]
Make projects on submission and observation pages hyperlinked to project pages

**Comment by kcs3** [comment]
Now that we have stable URLs, this should be easier to implement.

**Comment by zhouji2013** [comment]
We will make the project description on the submission page and the observation page a hyperlink to the project view. 

- An example of the project description on the submission page is "Dependency of clear-cell carcinoma cells on GPX4" on https://ctd2-dashboard.nci.nih.gov/dashboard/#submission/20190506-broad-ccc-gpx4-tier2
- An example of the project description on the observation page is "Dependency of clear-cell carcinoma cells on GPX4" when you click on "show details" in the "Submission" section on https://ctd2-dashboard.nci.nih.gov/dashboard/#observation/20190506-broad-ccc-gpx4-tier2-0
- The corresponding hyperlink is https://ctd2-dashboard.nci.nih.gov/dashboard/#center/broad/dependency-of-clear-cell-carcinoma-cells-on-gpx4

**Comment by arisf** [comment]
Confirmed on development server.
