### ISSUE TITLE
New format for stable links in the Dashboard

### ISSUE THREAD

**Issue by vdancik** [CBIIT/nci-ctd2-dashboard#317]
**Centers**

_current_: `https://ctd2-dashboard.nci.nih.gov/#/center/<dashboardID>`
_new_: `https://ctd2-dashboard.nci.nih.gov/#center/<short_center_name>`

**Submissions**

_current_: `https://ctd2-dashboard.nci.nih.gov/#submission/<dashboardID>`
_new_: `https://ctd2-dashboard.nci.nih.gov/#submission/<submission_name>`

**Observations**

_current_: `https://ctd2-dashboard.nci.nih.gov/#/observation/<dashboardID>`
_new_: `https://ctd2-dashboard.nci.nih.gov/#observation/<submission_name>-<index>`

**Subjects**

_current_: `https://ctd2-dashboard.nci.nih.gov/#/subject/<dashboardID>`
_new_:

```
animal model: https://ctd2-dashboard.nci.nih.gov/#animal-model/<displayName>
cell sample: https://ctd2-dashboard.nci.nih.gov/#cell-sample/<displayName>
compound: https://ctd2-dashboard.nci.nih.gov/#compound/<displayName>
gene: https://ctd2-dashboard.nci.nih.gov/#gene/h/<human_symbol>
gene: https://ctd2-dashboard.nci.nih.gov/#gene/m/<mouse_symbol>
protein: https://ctd2-dashboard.nci.nih.gov/#protein/<UniProtID>
shrna: https://ctd2-dashboard.nci.nih.gov/#rna/<sequence>
tissue sample: https://ctd2-dashboard.nci.nih.gov/#tissue/<NCI-thesaurus_id>
transcript: https://ctd2-dashboard.nci.nih.gov/#transcript/<RefseqId>
```

**Stories**

_current_: NA
_new_: `https://ctd2-dashboard.nci.nih.gov/#story/<submission_name>`

**MRA**
There is a single Columbia observation with a special file of type "mra" which in turn is displayed using special code written just for this data type.  It is displayed in the main page, not a new page.  We propose to use the mra filename to form the stable URL.  (The existing file is "columbia_gbm_mra_networks.mra").

_current_: `https://ctd2-dashboard.nci.nih.gov/dashboard/#/evidence/1703229`
_new_: `https://ctd2-dashboard.nci.nih.gov/dashboard/#mra/<filename>`

**Based on the discussion last week**, all the displayNames mentioned in this comment are not the same displayName as used elsewhere in this project. Instead, it refers to the strings based on displayName and follow the guidelines entered as a new comment.

**Comment by vdancik** [comment]
short center names:
          - "Broad"
          - "CSHL"
          - "Columbia"
          - "DFCI"
          - "Emory"
          - "FHCR1"
          - "FHCR2"
          - "Stanford"
          - "TGRI"
          - "UCSD"
          - "UCSF1"
          - "UCSF2"
          - "UTMDA"
          - "UTSW"

**Comment by vdancik** [comment]
**Guidelines for Generating URLs for the CTD2 Dashboard Site**

Creating stable URLs is the top priority as they are changing with every new release of the Dashboard. To have a consistent and predictable format when a new piece of content is created for the site we start with the page title and follow the general guidelines listed below:
•	Keep URLs (including the http://) 100 characters or less 
•	Separate words with hyphens
•	Use lowercase letters, even for acronyms and proper nouns
•	Only change a URL if absolutely necessary because every time a URL is re-directed, that page will experience a dip in search engine traffic.

**Comment by zhouji2013** [comment]
Shouldn't the "animal_model" and "cell_sample" in the URL's to be "animal-model" and "cell-sample" to be consistent with the format guidelines?

**Comment by zhouji2013** [comment]
Because there is no displayName for transcripts, we have to change the original requirement for transcript URL. After consulting Ken, I will change in the main description to RefseqId.

**Comment by kcs3** [comment]
Tested in production.  Closing issue.
