### ISSUE TITLE
Data Portal icon on the landing page should be removed

### ISSUE THREAD

**Issue by jagus7** [CBIIT/nci-ctd2-dashboard#319]
Data Portal icon displayed on the top-right corner of the landing page is distracting. This has to be replaced because there is a possibility that users may think that the clickable icon is the link to the Dashboard.

**Comment by kcs3** [comment]
This icon may be replaced by a link to a new tutorial.

**Comment by kcs3** [comment]
completed as part of #362

**Comment by kcs3** [comment]
Tested and confirmed working in production Dashboard version 2.50.
