### ISSUE TITLE
Brief Description of "Gene Cart" on the landing page

### ISSUE THREAD

**Issue by jagus7** [CBIIT/nci-ctd2-dashboard#321]
A brief description of the gene-cart as a mouse-over on the landing page should be added.

**Comment by kcs3** [comment]
Suggested hover text:  "Build or edit a list of genes and query for molecular interactions".

**Comment by zhouji2013** [comment]
hover text over what element on the page?

**Comment by kcs3** [comment]
I guess on the gene cart menu pulldown itself....

**Comment by kcs3** [comment]
OK it is a little weird looking to have a hover text which is then replaced by a pulldown menu, but it is worth a try to see what people think.

Tested on local instance.

**Comment by kcs3** [comment]
Tested on production release v3.40.
