### ISSUE TITLE
Add a download button/link to the tables

### ISSUE THREAD

**Issue by armish** [CBIIT/nci-ctd2-dashboard#323]
There are two options here:

* Target modern browsers and let the frontend prompt the user for a file download (won't work in legacy browsers)
* Implement a really simple backend point that we post the contents of the table to and let it set the proper headers and prompt the user for a download (common trick that works for all browsers)

There should already be `datatable` extensions that will allow either of these.

**Comment by hermidalc** [comment]
Some datatable extension like this would work https://datatables.net/extensions/buttons/examples/initialisation/export.html

**Comment by armish** [comment]
Closed via https://github.com/CBIIT/nci-ctd2-dashboard/commit/bdf5b43862ad238918c79d458435537a21a10a2d and https://github.com/CBIIT/nci-ctd2-dashboard/commit/607932e2d520a6f9fa2932e67412744c50c45850 by @zhouji2013.
