### ISSUE TITLE
Gene Cart Export Option

### ISSUE THREAD

**Issue by jagus7** [CBIIT/nci-ctd2-dashboard#331]
![genecartexport](https://user-images.githubusercontent.com/17437681/27091414-09624308-502e-11e7-86dc-9b9d47010df1.PNG)

Export option on top of the table is not prominent; may be we should use a different font/color?

**Comment by kcs3** [comment]
![gene_cart_query_export](https://user-images.githubusercontent.com/5807704/28791425-69805256-75fa-11e7-80b8-8dee7c5a5780.png)

The "Export" button should be directly above the check boxes.  "Showing 1 to 3 of 3 entries" should either be above "Export" or to the right of it.

**Comment by kcs3** [comment]
We think it is ok, it is consistent with other link-buttons on the page and in the Dashboard.
