### ISSUE TITLE
Submission helper error

### ISSUE THREAD

**Issue by vdancik** [CBIIT/nci-ctd2-dashboard#334]
I was helping DFCI center with a new submission and the following error kept popping up when trying to save the submission:

`error: <html><head><title>Apache - Error report</title><style><!--H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}HR {color : #525D76;}--></style> </head><body><h1>HTTP Status 404 - /submit/template/dataAccessFailure</h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p><p><b>message</b> <u>/submit/template/dataAccessFailure</u></p><p><b>description</b> <u>The requested resource is not available.</u></p><HR size="1" noshade="noshade"><h3>Apache</h3></body></html>`

**Comment by vdancik** [comment]
It appears that this error might be caused by entering an observation summary that is too long.

**Comment by kcs3** [comment]
Vlado reports that the original observation summary, which was too long, was as follows:

"Genome wide RNAi screens were performed in 501 cancer cell lines and through developing a DEMETER computational model that corrects for RNAi off-target effects strong differential dependencies and underlying predictive models were found, including a dependency of UBC that was associated with low expression of UBB as the top marker."

**Comment by kcs3** [comment]
We should test increasing the appropriate database field size and then instruct NCI what change to make on their database.

**Comment by vdancik** [comment]
Also check on client side that the length does not exceed the limit before sending it over.

**Comment by vdancik** [comment]
The field length limits in the Dashboard's main database (and after # a java class in which the limit is defined):

`MAX_LENGTH = {`

`    'display_name':255, # DashboardEntity`

`    'template_description':1024, 'observation_summary':1024, 'submission_name':128, 'submission_description':1024, 'project':1024, 'principal_investigator': 64, # ObservationTemplate`

`    'url': 2048, # UrlEvidence`

`    'file_path':1024, 'file_name':1024, 'mime_type': 256, # FileEvidence`

`    'subject_display_text':10240, 'subject_column_name': 1024, # ObservedSubjectRole`

`    'evidence_display_text':10240, 'evidence_column_name': 1024, 'attribute': 128, # ObservedEvidenceRole`

`    'units': 32, # DataNumericValue`

`    'role': 128, # SubjectWithSummaries`

`    'sequence':2048, 'type':5, 'reagent_name':255, # ShRna`

`    'smiles':2048, # CompoundImpl`

`    'gene_id':32, 'gene_symbol':32, # GeneImpl`

`    'annotation_source':128, 'annotation_type':128, # AnnotationImpl`

`    'database_id':128, 'database_name':128 # XrefImpl`

`}`

**Comment by kcs3** [comment]
Interestingly, the original offending observation summary is only 335 characters....

**Comment by kcs3** [comment]
The following shortened text for observation summary works does not cause an error:

Genome wide RNAi screens were performed in 501 cancer cell lines and through developing a DEMETER computational model that corrects for RNAi off-target effects strong differential dependencies and underlying

**Comment by kcs3** [comment]
Closing in favor of https://github.com/CBIIT/nci-ctd2-dashboard-tmpl-helper/issues/14
