### ISSUE TITLE
Submission helper export issue - display text in lower case

### ISSUE THREAD

**Issue by vdancik** [CBIIT/nci-ctd2-dashboard#335]
For some strange reason display text for evidence columns is all lower case. I logged-in the helper and the capitalization is correct there - I just copied the properly-capitalized text to the spreadsheet. (The capitalization of subject columns appears to be correct).

**Comment by kcs3** [comment]
Closing in favor of https://github.com/CBIIT/nci-ctd2-dashboard-tmpl-helper/issues/4
