### ISSUE TITLE
Submission helper export issue - mime_type

### ISSUE THREAD

**Issue by vdancik** [CBIIT/nci-ctd2-dashboard#337]
The correct row name for mime types is "mime_type" instead of "mime_types". 

The mime_type for images should be "image/jpg" or "image/png", depending on the file extension. The mime_type for stories should be "text/html", depending on the file extension.

**Comment by kcs3** [comment]
Closing in favor of https://github.com/CBIIT/nci-ctd2-dashboard-tmpl-helper/issues/6
