### ISSUE TITLE
Add New CTD^2 Centers to the Dashboard

### ISSUE THREAD

**Issue by jagus7** [CBIIT/nci-ctd2-dashboard#342]
Three new CTD^2 Centers Johns Hopkins University, Oregon Health & Science University, and University of California San Diego has to be added to the main Dashboard.

**Comment by zhouji2013** [comment]
Two logo images are needed for each center: one used on the stories page, stored in subdirectory img/slogos; the other used on the centers page and everywhere else, stored under subdirectory img

**Comment by zhouji2013** [comment]
All the required changes are done except for pending information for the new centers' links to https://ocg.cancer.gov/programs/ctd2/centers

For the new centers to show up on the web UI, the database needs to be updated with the new script in the repository.

**Comment by zhouji2013** [comment]
See #349

**Comment by kcs3** [comment]
Testing completed.  Leaving issue open till production database updated with script.

**Comment by kcs3** [comment]
Only Centers that actually have submissions appear on the Centers page.  Therefore, the changes made to the production database are lost after a new release.

**Comment by kcs3** [comment]
Closing issue.
