### ISSUE TITLE
implement new search behavior

### ISSUE THREAD

**Issue by zhouji2013** [CBIIT/nci-ctd2-dashboard#343]
As originally implemented, the "search" box on the CTD2 Dashboard web page returns results independently for each subject term entered; this is a logical "OR" operation. The search results are presented in a table with the following five columns: Name, Synonyms, Type, Roles, and Observations. In Observations, the number of matching observations is shown as a hyperlink to the actual observations themselves. As each search term is listed separately, there is no way to discern which observations may have matched more than one of the search terms.

In addition, if any submissions match the search term directly, (e.g. perhaps in their descriptive text), these submissions are displayed below the subject-level results table described above.

Requested change:

If only one search term is entered, the behavior is unchanged; the result table and any matching submissions are shown.
If more than one search term is entered, the result table and matching submissions are displayed as before, but below, list those observations which match all entered search terms are displayed, that is, the logical "AND".
This list of matching observations should have a title, "Observations Matching all Search Terms"
We may wish to re-examine whether to also filtered returned submissions so that only those matching all search terms are displayed, but this will be in a second phase.

- by Ken

**Comment by zhouji2013** [comment]
Results table:
![31622511-9bd98ab8-b26a-11e7-8618-6f46eb43858d](https://user-images.githubusercontent.com/5490096/31628415-9c119f8e-b27e-11e7-84f0-9df06d592821.png)

![31623821-ab433e3c-b26e-11e7-80ab-1ccb6fd9f05e](https://user-images.githubusercontent.com/5490096/31628425-a13f34ee-b27e-11e7-99fb-d5d6291e2a9d.png)

**Comment by zhouji2013** [comment]
implementation committed to a new branch "new_search_behavior"

**Comment by kcs3** [comment]
Change the "Submissions" heading in the results to read "Submissions Matching any Search Term".

**Comment by kcs3** [comment]
Note that search does not make use of subject synonyms, e.g. "gbm" does not match "glioblastoma".  Not a part of this issue.

**Comment by kcs3** [comment]
Note that search on multiple terms which include "*" wildcards, e.g. MAP2*, is not currently supported.  Only exact matches are currently supported.

**Comment by kcs3** [comment]
In issue #351, various improvements to the search examples are made, including adding multiple term search example and text.

**Comment by kcs3** [comment]
Assigning back to Zhou for making the change noted above, in the search results:

Change the "Submissions" heading in the results to read "Submissions Matching any Search Term".

**Comment by kcs3** [comment]
The change to the Submission title is verified.  Testing of search shows working as expected.  Notes above on synonyms and wildcards should be entered as new issues (enhancements).

**Comment by kcs3** [comment]
Search branch looks ready for merge back to master.

**Comment by zhouji2013** [comment]
merged

**Comment by kcs3** [comment]
The final implementation of search on more than one search time is as follows:
The first section of search results shows entries for each term individually, with a count of the number of observations in which the term occurs.
The second section is titled "Submissions Matching any Search Term" and matches terms appearing in the "Description" of the submission.
The third section is new: "Observations Matching all Search Terms".  It shows only those observations that match all search terms.

**Comment by kcs3** [comment]
Except as noted in new issue #353, the search behavior in production is verified as working as described in the previous note.

Closing issue.
