### ISSUE TITLE
Dashboard Landing Page Text

### ISSUE THREAD

**Issue by birrielpc** [CBIIT/nci-ctd2-dashboard#344]
Please update the current text on the Dashboard landing page with revised text in the attached Word document.
[DB_LandingPageText_Final.docx](https://github.com/CBIIT/nci-ctd2-dashboard/files/1398561/DB_LandingPageText_Final.docx)

**Comment by zhouji2013** [comment]
done

**Comment by kcs3** [comment]
Small grammatical change to supplied text.  Closing issue.
