### ISSUE TITLE
"Tier" Definition as Hover-Over on Dashboard Landing Page

### ISSUE THREAD

**Issue by birrielpc** [CBIIT/nci-ctd2-dashboard#345]
On the Dashboard landing page, please include the definition attached for "Tier" as a hover-over option for the corresponding text.
[Tier_Definition_DBLandingPageText_Final.docx](https://github.com/CBIIT/nci-ctd2-dashboard/files/1398609/Tier_Definition_DBLandingPageText_Final.docx)

**Comment by zhouji2013** [comment]
ready for test

**Comment by kcs3** [comment]
The hover text has been added.  The default formatting is "centered", which could be improved on with additional work.
