### ISSUE TITLE
Text for 'Navigating and Understanding Dashboard Content'

### ISSUE THREAD

**Issue by birrielpc** [CBIIT/nci-ctd2-dashboard#346]
Please update the text that appears when clicking on the "Navigating and Understanding Dashboard Content" hyperlink within the Dashboard landing page, with the text in the attached Word document.
[Navigating_and_Understanding_DB_Content_Text_Final.docx](https://github.com/CBIIT/nci-ctd2-dashboard/files/1398695/Navigating_and_Understanding_DB_Content_Text_Final.docx)

**Comment by zhouji2013** [comment]
done

**Comment by kcs3** [comment]
Changed description of how to calculate relevance score.  Closing issue.
