### ISSUE TITLE
Dashboard Footer Text

### ISSUE THREAD

**Issue by birrielpc** [CBIIT/nci-ctd2-dashboard#347]
Please update the text within the footer of the Dashboard page with the text in the attached document.
[DB_Footer_Text_Final.docx](https://github.com/CBIIT/nci-ctd2-dashboard/files/1398732/DB_Footer_Text_Final.docx)

**Comment by zhouji2013** [comment]
done

**Comment by birrielpc** [comment]
Hello. I just realized that the link to "Aksoy, Dančík, Smith et al." was incorrect. I apologize; may that link be updated to: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5569694/
Thank you!

**Comment by zhouji2013** [comment]
@birrielpc updated accordingly

**Comment by kcs3** [comment]
Update confirmed correct.  Closing issue.
