### ISSUE TITLE
ctd2-dashboard seed database cannot be downloaded because link is not accessible to broad public

### ISSUE THREAD

**Issue by yanickpouliot** [CBIIT/nci-ctd2-dashboard#348]
Howdy. The link for the seed database for CTD2 dashboard on https://github.com/CBIIT/nci-ctd2-dashboard/wiki/Dashboard-Admin-Tool points to a bitbucket repo that requires a user to have a login to the BB repo. The short of it is that a third party like me cannot download the DB and populate a local CTD2 dashboard. Can you address, please?

Here is the link in question: https://bitbucket.org/cbio_mskcc/ctd2-dashboard/downloads/ctd2-dashboard-seed.zip.

Thx!

Yannick

**Comment by jagus7** [comment]
Dashboard team decided to post a copy of the downloadable Zip file on the DCC server under the Dashboard submissions and provide the link on the GitHub site under “Releases” and a copy on the Dashboard under resources as “Dashboard Data”.

**Comment by kcs3** [comment]
What is the link to the Dashboard data on the DCC server?

I do not see the link on Github under releases.  

Add the link as requested above to Github and to the Resources menu of the Dashboard.

**Comment by zhouji2013** [comment]
What is the link to added?

**Comment by kcs3** [comment]
It seems that the load file will be maintained on the CDT2 Data Portal.

**Comment by kcs3** [comment]
Closing issue.
