### ISSUE TITLE
Update Centers Descriptions

### ISSUE THREAD

**Issue by birrielpc** [CBIIT/nci-ctd2-dashboard#349]
Please update the "(view center description)" links for all Centers with the updated links found in the attached table. Additionally, the Principal Investigators of the three new Centers are listed in the table, as this information will be needed for future submissions.
[CTD^2_Centers_Updated_Links_and_PIs.docx](https://github.com/CBIIT/nci-ctd2-dashboard/files/1419811/CTD.2_Centers_Updated_Links_and_PIs.docx)

**Comment by zhouji2013** [comment]
This is really part of #342

**Comment by kcs3** [comment]
Verified.  Note that the new PIs, as they as yet have no submissions, do not appear in the main "Centers" listing.  But that is another issue entirely.
Closing issue.
