### ISSUE TITLE
Uniprot link-outs use invalid URL

### ISSUE THREAD

**Issue by kcs3** [CBIIT/nci-ctd2-dashboard#352]
Uniprot IDs in Protein subject entries link out to uniprot.com/id, where id is for example P01731, so uniprot.com/P01731.  However, uniprot.com does not exist.

A URL that works is www.uniprot.org/uniprot/id, eg. http://www.uniprot.org/uniprot/P01731.

Btw it looks like https is not supported.

**Comment by kcs3** [comment]
This problem is only on the Protein pages, not on the Gene pages. (Reported by Vlado).

**Comment by vdancik** [comment]
The information about proteins (or transcripts) is not provided when data package is created, they must be created downstream.

It's only protein pages that exhibit this problem - links are correct on gene pages

**Comment by kcs3** [comment]
To see that this is fixed, go to the Dashboard gene page for any gene, e.g. FOSL2.  There is a link out to UniProt.  Clicking on this link now correctly opens the page for the protein at uniprot.org.

Closing issue.
