### ISSUE TITLE
In Internet Explorer, List Boxes are Empty When Selecting Interactome Name and Version

### ISSUE THREAD

**Issue by birrielpc** [CBIIT/nci-ctd2-dashboard#354]
On this page: https://ctd2-dashboard.nci.nih.gov/dashboard/#cnkb-query the list that should show up under "Select Interactome" is empty when using Internet Explorer.

**Comment by kcs3** [comment]
It was agreed that Internet Explorer will not be further supported by the Dashboard.  The Dashboard footer states that the preferred browser is Chrome.
