### ISSUE TITLE
Replace Principal Investigator Name for UCSF (1)

### ISSUE THREAD

**Issue by birrielpc** [CBIIT/nci-ctd2-dashboard#355]
Please replace the Principal Investigator for the University of California San Francisco (1) from Frank P. McCormick, Ph.D. to Michael McManus, Ph.D.

**Comment by kcs3** [comment]
The PI name displayed in the Centers page comes from the actual submissions, so as currently coded we can't just change it.  We also don't know at the moment which name will be displayed when submissions from the different PIs for one Center are added.  

What is the desired behavior?  To only show the latest PI, even when some submissions are attributed to the earlier PI?

**Comment by jagus7** [comment]
Yes, we would like the PI name to be replaced in all the submissions made by UCSF (1) Center as Dr. McManus replaced Dr. McCormick. I will assign this issue to Vlado.

**Comment by vdancik** [comment]
Done
