### ISSUE TITLE
searching for words that have dashes in them

### ISSUE THREAD

**Issue by kcs3** [CBIIT/nci-ctd2-dashboard#356]
Searching on "b cell" matches NCI Thesaurus terms (subjects) with  B-cell.  However, including the dash in the search,  e.g. searching on "B-cell", causes no hits to be returned.  Note that actually including quotes in the search does not change this particular behavior as far as the dashes goes, but does change the terms hit.

**Comment by vdancik** [comment]
The same problem probably applies to searching for subjects containing other punctuation, like commas. Good example is compound '1S,3R-RSL-3', which cannot be search for by neither of `1S,3R-RSL-3`, `1S,3R`, or `1S,3R*`, but can be found by searching `1S`.

**Comment by kcs3** [comment]
It turns out that synonyms are matched using a different method than subjects.  Examples of synonyms not currently matched are "BRD-K38775274", "PKB-ALPHA", and "PKB/Akt".

**Comment by kcs3** [comment]
As far as testing subjects, "ABT-737" from issue #369 now works, as does "B-cell". Note that specifying "B-cell" returns only terms including the dash, but searching on "B cell" returns a large number of unrelated terms matching "B" but not cell.

**Comment by kcs3** [comment]
Other terms tested: "SR-II-138A", "SR-II*", 

Terms tested unrelated to the current issue:
""hepatocellular carcinoma"" with quotes, which do work to restrict the match to both terms appearing together, and "hepatocellular*carcinoma" which matches only the single term with only those two words (interesting behavior).

**Comment by kcs3** [comment]
Tested indexing of synonyms with special characters.  Searching on "BRD-K38775274", "PKB-ALPHA", and "PKB/Akt" all succeed now.

**Comment by kcs3** [comment]
Tested in production release v2.53.1_20180514.  The fixes do not appear to have made it to production. 
 Searching on "BRD-K38775274", "PKB-ALPHA", and "PKB/Akt" do not give any results.

**Comment by zhouji2013** [comment]
The last issue reported turned out to be some deployment problem and has been fixed.

**Comment by kcs3** [comment]
Following redeployment on the NCI production server, I tested the following search terms, all worked unless otherwise noted:
B-cell
1S,3R-RSL-3
1S,3R*
1S,3R ( does not match but it is just a partial match)
PKB/Akt
PKB-ALPHA

Everything looks good.  Zhou has also tested.
Confirmed issue is resolved and closing issue.
