### ISSUE TITLE
limit number of observations displayed from a single submission

### ISSUE THREAD

**Issue by kcs3** [CBIIT/nci-ctd2-dashboard#357]
Some submissions may have hundreds of observations, for example from a large screen.  In general this should not be a problem, as any query that goes across observations will probably only hit a small number from any one observation.  However, we should be on the lookout for any cases where this does become a problem.  If this were to come up, we could look into limiting the number of observations from one submission directly displayed, and instead show a link "show remaining observations from this submission".

## update April 22, 2019 
Here is the [Google Doc file](https://docs.google.com/document/d/13Ux0GfoaOGzHMNB7YrJTmQzn3XFk2x0l3PCvOQqx3gE/edit) that contains more details about what is planned to do with this issue (as of 4/2/2019). At April 3rd WG Teleconference, it is agreed (beyond what is in the document) that the key change will be: initially, only retrieve one observation from each submission, and only when the user chooses to 'expand' the result, all the other observations are retrieved. This is different from the earlier proposal of collapsing observations initially for each submission on the frontend. The new design will be more responsive in case there are a large number of observations to be retrieved, and probably will eliminate the need to have a limited subset retrieved first as the system works now.

**Comment by birrielpc** [comment]
Implement the expandable block “+” option for submissions having hundreds of observations from a single methodological study. Additionally, if possible give an order of significance to the observations to help users in understanding the importance of the submission. This may require the submitter or the software to determine which is the most prominent.

**Comment by kcs3** [comment]
This was originally proposed by Leandro in issue #157

**Comment by kcs3** [comment]
The expandable clamshell operation is working as designed.  Including some ordering to the observations is an unrelated issue for another day.
