### ISSUE TITLE
Superscript "2" within sentence on landing page

### ISSUE THREAD

**Issue by birrielpc** [CBIIT/nci-ctd2-dashboard#359]
Please update "CTD2" within the current text on the Dashboard landing page by superscripting the "2"
More specifically, within this sentence: "In summary, the Dashboard provides access to validated data and the ability to view a cross-section of results assembled across multiple **CTD2** Center findings."

**Comment by kcs3** [comment]
Tested and confirmed working in production Dashboard version 2.50.
