### ISSUE TITLE
Add Dashboard Videos Framework 

### ISSUE THREAD

**Issue by birrielpc** [CBIIT/nci-ctd2-dashboard#362]
Please add the "CTD^2 Dashboard Tutorial Videos" framework that is currently being used on the right hand side of OCG CTD^2 site: https://ocg.cancer.gov/programs/ctd2

**Comment by kcs3** [comment]
Do you want us to replace the current Data Portal icon on the home page with the "CTD² DASHBOARD TUTORIAL VIDEOS" graphic shown on the OCG site, and implement the three links to videos as shown there?

**Comment by kcs3** [comment]
Subhashini wrote: "In order to be consistent across the sites, we would like to use the graphic and links to three videos as it is implemented on the OCG site on the Dashboard website as well. Please remove the Data Portal icon we have on the landing page."

**Comment by kcs3** [comment]
Tested and verified working on production release 2.50.
