### ISSUE TITLE
Support for additional subject links

### ISSUE THREAD

**Issue by vdancik** [CBIIT/nci-ctd2-dashboard#364]
Update the Dashboard's admin tool to support upload of cross-reference information for subjects.

**Comment by kcs3** [comment]
Links to Drug Bank appeared in Release 2.51.

**Comment by birrielpc** [comment]
Link to NCI Genomic Data Commons (GDC) Data Analysis, Visualization, and Exploration (DAVE) Tools:
https://gdc.cancer.gov/analyze-data/gdc-dave-tools

**Comment by kcs3** [comment]
A new issue will be created for each new link type added.  A list of such links requested and implemented is maintained in a Google Sheet. Closing this issue.
