### ISSUE TITLE
In search box hover text, compound example is incorrect

### ISSUE THREAD

**Issue by kcs3** [CBIIT/nci-ctd2-dashboard#369]
The existing search example is "ABT-737".  This compound is not present in the dashboard.  We will use "dasatinib" instead, which has observations from multiple centers.

**Comment by vdancik** [comment]
Actually, compound example is correct, it's the search that does not work. ABT-737 is a present and has 141 observations:

`https://ctd2-dashboard.nci.nih.gov/dashboard/#subject/465312`

It can be discovered by searching for `ABT*`

**Comment by kcs3** [comment]
This relates to issue #356, which reports that searches for terms with dashes do not work.

**Comment by kcs3** [comment]
"bug" and "major" labels transferred to #356.

**Comment by kcs3** [comment]
Tested on production, closing issue.

**Comment by kcs3** [comment]
As far as testing subjects, "ABT-737" from issue #369 now works, as does "B-cell".  Note that specifying "B-cell" returns only terms including the dash, but searching on "B cell" returns a large number of unrelated terms matching "B" but not cell.
