### ISSUE TITLE
Additional changes for stable URLs

### ISSUE THREAD

**Issue by kcs3** [CBIIT/nci-ctd2-dashboard#371]
Issue #317 covered converting URLs to use stable identifiers rather than internal database keys, and also set out a format which replaced spaces and other non-alphanumeric characters with dashes.  The description applied to database entities such as Subjects, Centers, Submissions, Objects and Stories.

However, there are additional URL types generated by the Dashboard.  Although internal database keys will not appear in them, the URL text formatting has not been changed to e.g. eliminate spaces.

Affected are:
Project titles - these are an extension of the "Centers" URL and are seen when browsing by Center.

**Comment by zhouji2013** [comment]
implemented in 45c79f6

**Comment by kcs3** [comment]
Tested project title URLs by copying to different browser, works fine.

**Comment by kcs3** [comment]
Verified working in production.  Tested by copying URLs to another browser.
Closing issue.
