### ISSUE TITLE
API: missing observation values 

### ISSUE THREAD

**Issue by vdancik** [CBIIT/nci-ctd2-dashboard#373]
> CTD2 Dashboard API #370

Label and URL evidence classes have missing values

**Comment by zhouji2013** [comment]
I did not close this manually. This happened automatically by code-merging.

**Comment by vdancik** [comment]
Labels and URLs now have appropriate values. Verified by the following call:

https://ctd2-dashboard.nci.nih.gov/dashboard/api/submission/20140328-mskcc-pdgfrb-imatinib
