### ISSUE TITLE
API: wrong submission id

### ISSUE THREAD

**Issue by vdancik** [CBIIT/nci-ctd2-dashboard#374]
> CTD2 Dashboard API #370

Wrong submission id in centers list and observations lists

**Comment by kcs3** [comment]
Further detail from Vlado's email:
"submission_id uses old unstable id rather then new stable submission id."

**Comment by zhouji2013** [comment]
I did not close this manually. This happened automatically by code-merging.

**Comment by vdancik** [comment]
Correct submission id is now returned. Verified by the following call:

https://ctd2-dashboard.nci.nih.gov/dashboard/api/centers
