### ISSUE TITLE
API implementation - wrong class names used.

### ISSUE THREAD

**Issue by kcs3** [CBIIT/nci-ctd2-dashboard#375]
From Vlado's email:
"subject/evidence class uses underlying java class name instead of a simple names: label, url, numeric, file, tissue, gene, ..."

**Comment by zhouji2013** [comment]
This was changed yesterday b351ffc

**Comment by vdancik** [comment]
Subject and evidence classes are now simple names instead of java class names. Verified by the following call:

https://ctd2-dashboard.nci.nih.gov/dashboard/api/submission/20140328-mskcc-pdgfrb-imatinib
