### ISSUE TITLE
Issues with Site When Using Shortened URL Links 

### ISSUE THREAD

**Issue by birrielpc** [CBIIT/nci-ctd2-dashboard#378]
Tracx Software (https://www.tracx.com/) allows for the Center for Cancer Genomics team to draft content that gets approved and tweeted at a later date through the @NCIgenomics Twitter account. Tracx is able to shorten URLs by adding ?cid=tw to the original URL.

For example, the Dashboard story: https://ctd2-dashboard.nci.nih.gov/dashboard/#story/20180412-broad-gpx4-story got shortened to: http://bit.ly/2LdK4X9

But, that causes the URL on the Dashboard site to not work when using the shortened URL. Is there a solution that could be implemented on the Dashboard site to not encounter this problem?

**Comment by kcs3** [comment]
The shortened URL http://bit.ly/2LdK4X9 expands back out to 
https://ctd2-dashboard.nci.nih.gov/dashboard/#story/20180412-broad-gpx4-story?cid=tw

That is, it still has the "?cid=tw" at the end.  If this were not present, the URL would work.

**Comment by birrielpc** [comment]
I was able to shorten the Dashboard story URL to: go.usa.gov/xQGJS

Tracx automatically adds "?cid=tw" at the end of the expanded original URL and cannot be removed.

**Comment by kcs3** [comment]
Both the bit.ly and the go.usa.gov versions now work in the Dashboard.
