### ISSUE TITLE
508-Compliance Issue: Text Elements Must Have Sufficient Color Contrast Against the Background

### ISSUE THREAD

**Issue by birrielpc** [CBIIT/nci-ctd2-dashboard#379]
A 508-compliance issue came up regarding the site's “Color Contrast” (i.e. text elements must have sufficient color contrast against the background). To fix this issue, the Dashboard site contrast between foreground and background colors needs to meet WCAG 2 AA contrast ratio thresholds.

The element source code provided is: "a href="#story-1" class="story-link">?????????</a" and the attachment provides further details from the WorldSpace report. 
[CTD^2_DB_508-Compliance_Report_7-11-18.pdf](https://github.com/CBIIT/nci-ctd2-dashboard/files/2202912/CTD.2_DB_508-Compliance_Report_7-11-18.pdf)

The issue can be fixed by ensuring all text elements have sufficient color contrast between the text in the foreground and background color behind it; the color contrast analyzer at the following link can be used to find colors that pass the guidelines: https://dequeuniversity.com/rules/axe/2.2/color-contrast?application=axeAPI

**Comment by kcs3** [comment]
Based on date, labeled as released in V2.54.
