### ISSUE TITLE
508-Compliance Issue: Form Elements Must Have Labels

### ISSUE THREAD

**Issue by birrielpc** [CBIIT/nci-ctd2-dashboard#380]
A 508-compliance issue came up regarding the site's “Label Forms” (i.e. form elements must have labels). To fix this issue, the Dashboard site needs to ensure that every form element has a programmatically associated label element.

The element source code provided is: input type="text" id="omni-input" class="span3 search-query" placeholder="e.g. CTNNB1 or ABT-737" data-original-title="Search" and the attachment provides further details from the WorldSpace report. 
[CTD^2_DB_508-Compliance_Report_7-11-18.pdf](https://github.com/CBIIT/nci-ctd2-dashboard/files/2202912/CTD.2_DB_508-Compliance_Report_7-11-18.pdf)

The issue can be fixed by programmatically associating labels to all form controls and ensuring there are no duplicate labels; this can be done by using an implicit "label", explicit "label", ‘aria-label’ or ‘aria-labelledby’ https://dequeuniversity.com/rules/axe/2.2/label?application=axeAPI

**Comment by zhouji2013** [comment]
There may be multiple cases of this issue. I only modified the specific one identified by the report. When the next scanning verifies that the modification does make it compliant, we will then make the change for other similar cases.

**Comment by kcs3** [comment]
Based on date, labeled as released in V2.54.
