### ISSUE TITLE
Stories not shown

### ISSUE THREAD

**Issue by vdancik** [CBIIT/nci-ctd2-dashboard#384]
The story text is not displayed when user clicks on "view full story" either on the landing page or on the story-list page

**Comment by vdancik** [comment]
Stories are back online

**Comment by kcs3** [comment]
This was an issue with NCI a change in depolyment software.

In an email dated August 29, 2018, Yiwen said:
"...I just heard from the host team that they’ve identified the issue with the deployment workflow, which was recently switched to Jenkins from AnthillPro. They deployed stage again and I can see the text of stories now. "
