### ISSUE TITLE
numbers of observations shown on subject page sometimes are not consistent

### ISSUE THREAD

**Issue by zhouji2013** [CBIIT/nci-ctd2-dashboard#386]
The problem showed in the warning message of too many observations. For example, on MYC page, https://ctd2-dashboard.nci.nih.gov/dashboard/#gene/h/myc, the message says "Only 100 of 222 observations are listed in the table below", but in fact, the table under it contains 86 instead 100 observations. The number 86 is displayed and it is the actual number of rows in the table. Then, if you click on the link on "To load all observations please click here", it loads 208 instead of 220 as it claims.

**Comment by zhouji2013** [comment]
The real bug is in WebServiceUtil.java. When we query observations based on a subject, duplicate observations are included because they are found through multiple instances of 'observed subject'. The problem shows up due to the front-end library's feature of automatically removing the duplicates. That is why we end up to have a smaller number than what the server-side sends. The smaller number is, in fact, the correct number,

**Comment by kcs3** [comment]
Seems to deliver consistent results now.
