### ISSUE TITLE
search-results summary

### ISSUE THREAD

**Issue by vdancik** [CBIIT/nci-ctd2-dashboard#390]
Provide a short summary of search results at the top of a search-results page summarizing (with links to the corresponding sections of the page):

- what was searched for
- how many matching subjects were found
- how many matching submissions were found
- how many matching observations were found

**Comment by kcs3** [comment]
No longer an issue after  redesign of search.

**Comment by kcs3** [comment]
The search result page already shows what was searched for at the top of the results.

As far as the remaining three points:

- how many matching subjects were found - this is shown in the subject results table and I don't think requires further summary.

- how many matching submissions were found  
- how many matching observations were found

For these two, Vlado has suggested adding links above all the search results, which would take the user to the relevant sections (which may or may not be present for a given search):

Submissions Matching any Search Term
Observations Matching all Search Terms

This can be done in simple fashion as:
See submissions matching any search term
See observations matching all search terms

A more elaborate scheme is to actually summarize relevant counts in the link names

(to be added....)

**Comment by kcs3** [comment]
Looks good.

**Comment by kcs3** [comment]
The enhancement was implemented as one line, with the submissions result separated from the observations result by a bar "|".  For example, searching on "dexamethasone AKT1" results in this result, where the new feature is the second line shown:

Search for dexamethasone AKT1
See 2 matched submissions from one center | See 6 observations matching all search terms

Tested on production release v3.40.
