### ISSUE TITLE
limit number of  search results

### ISSUE THREAD

**Issue by zhouji2013** [CBIIT/nci-ctd2-dashboard#392]
There is a configurable limit for the number of the results from the full-text search. It is set to be 200 in the current and previous releases. It limits the results to an arbitrary subset of what may be interesting.

I tested with the limit turned off, the results could easily be around 2000 or 3000. For example, 'lung carcinoma' returns 2,091subjects; 'kras lung carcinoma cell' returns 3,585 subjects. However, it became very slow for the application to respond, and also added risky memory burden both on the server side and on the front end. Sometimes the browser warned that the page was too slow and suggested the user stop the script.

We need to come up with a reasonably fast approach to present the complete picture of the search result.

**Comment by zhouji2013** [comment]
Based on the earlier discussion, this issue will be handled by an indirect but better approach: namely to exclude the subjects that are not included in any observations.

**Comment by kcs3** [comment]
"lung carcinoma" now returns 32 hits (one of which is "lung carcinoma").
"kras lung carcinoma cell" now returns 44 hits, including "KRAS" and "lung carcinoma".
"kras lung carcinoma" returns 36 hits, including "KRAS" and "lung carcinoma", and also entries under "Observations Matching all Search Terms".

Seems to all be working.
