### ISSUE TITLE
DrugBank link sometime does not show up

### ISSUE THREAD

**Issue by vdancik** [CBIIT/nci-ctd2-dashboard#397]
For example BRD63610 does have a DrugBank link, but bortezomib does not (both should have one):

https://ctd2-dashboard.nci.nih.gov/dashboard/#compound/brd63610
https://ctd2-dashboard.nci.nih.gov/dashboard/#compound/bortezomib

**Comment by kcs3** [comment]
Note: On the page for the first example URL above, for [BRD63610](https://ctd2-dashboard.nci.nih.gov/dashboard/#compound/brd63610), the [DrugBank link](https://www.drugbank.ca/drugs/DB07656) points to a revoked record.

**Comment by kcs3** [comment]
The bortezomib link works fine.
