### ISSUE TITLE
incorrect observation numbers in API result

### ISSUE THREAD

**Issue by zhouji2013** [CBIIT/nci-ctd2-dashboard#398]
In some of the results for API, the observation_count is incorrectly shown as 0. For example, in the result from https://ctd2-dashboard.nci.nih.gov/dashboard/api/centers, every center contains an array of submissions, and within each submission, there is an observation_count that is 0 for all cases.

This appears to be caused by a change made for an unrelated bug fix (#386). The code change there affects API inadvertently.

**Comment by zhouji2013** [comment]
another test case:
/dashboard/api/submission/20130402-broad-beta-catenin-navitoclax

**Comment by kcs3** [comment]
Works correctly now

**Comment by kcs3** [comment]
Verified fixed in production
