### ISSUE TITLE
Some of the Project links do not work correctly

### ISSUE THREAD

**Issue by zhouji2013** [CBIIT/nci-ctd2-dashboard#400]
Some of the Project links on the center page do not work when clicked on. It just redirects to the center page of all submissions. For example, for Columbia, you can see two such cases:
1. "Elucidating compound mechanism of action by network perturbation analysis" https://ctd2-dashboard.nci.nih.gov/dashboard/#center/columbia/elucidating-compound-mechanism-of-action-by-network-perturbation-analysis
2. "Identification of synergistic dependencies by proteome-wide signaling-network analysis" https://ctd2-dashboard.nci.nih.gov/dashboard/#center/columbia/identification-of-synergistic-dependencies-by-proteome-wide-signaling-network-analysis

**Comment by zhouji2013** [comment]
This is an intricate bug in the way of how those links are created.

**Comment by kcs3** [comment]
Verified that these project links do point to themselves now.
