### ISSUE TITLE
Evidences not shown for some submission

### ISSUE THREAD

**Issue by zhouji2013** [CBIIT/nci-ctd2-dashboard#401]
The evidence section of the observation view is empty for all 11 observations of this particular submission: "Synergistic effects of EGFR and c-MET inhibitors were validated in multiple LUAD cell lines using colony formation assays." https://ctd2-dashboard.nci.nih.gov/dashboard/#submission/20190212-columbia-paracne-1-colony

**Comment by zhouji2013** [comment]
This is caused by the first evidence in this submission, whose evidence type is 'label' but evidence role 'measured'. The code handling ECO terms expects a fixed set of combinations of those two fields. In this case of unexpected combination, it breaks down and causes the following process (displaying evidence on the page) not happening.

**Comment by zhouji2013** [comment]
The code was changed to handle such a situation although the data may need to be fixed as well in this particular case because it does not look intentional.

**Comment by vdancik** [comment]
The label/measured combo is also present in https://ctd2-dashboard.nci.nih.gov/dashboard/#submission/20190201-emory-htip-iap-antagonists-antitumo submission and is intended to be such.

**Comment by zhouji2013** [comment]
When I tested this issue, I noticed that the ECO term links themselves have stopped showing in the current release.

**Comment by zhouji2013** [comment]
> 
> 
> The label/measured combo is also present in https://ctd2-dashboard.nci.nih.gov/dashboard/#submission/20190201-emory-htip-iap-antagonists-antitumo submission and is intended to be such.

It's nice to have this additional case documented here. In this case, the first evidence shows up, but the other 4 evidences (out of totally 5) do not show up because of this bug.

**Comment by kcs3** [comment]
Out of curiosity: In these examples the actual value type is a number, why was "label" chosen for the evidence type rather than "numeric" by the submitter?  Is it because the values include the standard deviation or SE, e.g. 5 +- 1?

**Comment by kcs3** [comment]
For the two submissions described above, all of the evidence rows in each observation are now showing up properly.
