### ISSUE TITLE
Add links to DepMap

### ISSUE THREAD

**Issue by vdancik** [CBIIT/nci-ctd2-dashboard#404]
Add links to DepMap (https://depmap.org)

**Comment by kcs3** [comment]
I see DepMap links in release 3.2.  Assuming this is done.

**Comment by kcs3** [comment]
Examples for DepMap:
- Compound: https://ctd2-dashboard.nci.nih.gov/dashboard/#compound/dasatinib
- Cell Sample: https://ctd2-dashboard.nci.nih.gov/dashboard/#cell-sample/ncih1299
