### ISSUE TITLE
Allow stories to be sorted by Center

### ISSUE THREAD

**Issue by kcs3** [CBIIT/nci-ctd2-dashboard#406]
In #233, it was suggested that the stories page should be sortable by Center.

https://ctd2-dashboard.nci.nih.gov/dashboard/#stories

**Comment by jagus7** [comment]
Carousel feature for the "Stories" is not working, only first story title is shown. Is it possible to make it work?

**Comment by kcs3** [comment]
It seems like the Stories page
https://ctd2-dashboard.nci.nih.gov/dashboard/#stories
should indeed by sortable by Center or date.  Also provide reset to default (original) order?

**Comment by kcs3** [comment]
Please make the stories page https://ctd2-dashboard.nci.nih.gov/dashboard/#stories sortable by Center and by Date.  The default order should remain as it is now, by date.

**Comment by kcs3** [comment]
Tested on local instance.  Works fine.

**Comment by kcs3** [comment]
Tested on production release v3.40.
