### ISSUE TITLE
Stories Carousel Feature -Bug

### ISSUE THREAD

**Issue by jagus7** [CBIIT/nci-ctd2-dashboard#407]
Carousel feature for the "Stories" is not working, only first story title is shown. Is it possible to make it work?

**Comment by zhouji2013** [comment]
This is implemented as following: 
- after every 5 seconds, the story displayed is switched to the next available and it returns to the first one when all available are used
- the existing manual selection by the 'dot' button is left as is, meaning that if it is clicked at any time, it shows the corresponding story

**Comment by kcs3** [comment]
Verfied fixed in production.  Final time between stories is currently 12 seconds.  This because if the user is navigating in the pull-down menus, the page is refreshed when the stories change and the user must restart navigating.
