### ISSUE TITLE
Show element categories even if ‘Select Roles’ is not pressed

### ISSUE THREAD

**Issue by jagus7** [CBIIT/nci-ctd2-dashboard#410]
Part of feedback provided by Kwat (UCSD).  Currently, explore " Genes and Proteins" default display roles are "target and biomarker".  I think the suggestion is to display all roles by default. I noticed that hover-over text on "Select Roles" on all Browse pages is displayed as " Role (biomarker, perturbagen, etc.). As, "perturbagen"  is not a rule under "Genes and Proteins"  and "Disease Context", it may confuse the users. I think we should customize the text to the "Browse" pages.

**Comment by kcs3** [comment]
Add perturbagen role to gene browse page.

**Comment by zhouji2013** [comment]
Ken's comment and the original report seems two independent requests.

**Comment by kcs3** [comment]
Suggestion 1:

1. - For Genes, change hover text to "Target, biomarker, etc.".  No need to have "Role", as that is already specified in the button name.
2. - For Compounds and Perturbagens, change hover text to "Perturbagen, candidate drug, control compound"
3. - For Disease Context, change hover text to "Disease, Metastatis, Tissue"

Suggestion 2:  instead, come up with a single descriptive hover-text for all three states.

**Comment by kcs3** [comment]
tested on local instance, looks good.

**Comment by kcs3** [comment]
Tested on production release v3.40.  Note that the hover text for the new browse category of Cell Lines was also added, for which the only available role is cell line..
