### ISSUE TITLE
●	In the Centers section of the Dashboard only ‘Center’ name can be sorted, but all of the headers have sort buttons

### ISSUE THREAD

**Issue by jagus7** [CBIIT/nci-ctd2-dashboard#412]

**Comment by kcs3** [comment]
Tested on local development server, the change is that sorting is disabled on all except the Center Name column

**Comment by kcs3** [comment]
Tested on production release v3.40.  The table can be sorted by Center or by number of Submissions.  The other two columns no longer have sort enabled.
