### ISSUE TITLE
●	Add FDA status or approval status (in other diseases) to ‘Explore Perturbagens, Candidate Drugs’ page

### ISSUE THREAD

**Issue by jagus7** [CBIIT/nci-ctd2-dashboard#417]

**Comment by kcs3** [comment]
This information is available in the e.g. the DrugBank linkout from the subject page.

**Comment by kcs3** [comment]
Vlado - is there any reason to try to provide this info directly in the Dashboard?  I think the linkouts are the way to go.

**Comment by vdancik** [comment]
It is not plausible to maintain such information, it is available from DrugBank and DepMap links.

**Comment by kcs3** [comment]
Closing issue, data is already available.
