### ISSUE TITLE
Define Oncogenes

### ISSUE THREAD

**Issue by jagus7** [CBIIT/nci-ctd2-dashboard#418]
Kwat said TP53, PTEN, and some other tumor suppressors are validated as oncogenes; so, providing definition of "Oncogenes" is helpful and add "Tumor Suppressor" class

**Comment by kcs3** [comment]
Roles are dynamic, they are not hard-coded as far as upload process.  So we can add support to the Submission Builder now.  If any such submissions occur, can add to Dashboard.

**Comment by kcs3** [comment]
Copying text from duplicate issue #461 and closing that issue:

"Add definitions for each role to the role selection panels as hover-text and to the “background information” link, e.g., for “oncogene”. Add a new role “tumor suppressor”.

**Comment by kcs3** [comment]
As far as I can see, we have not implemented hover-text for any roles in the Dashboard.  Here are definitions that appear in the Submission Builder manual:

- target - a gene or protein targeted by chemical or genetic perturbagens
- biomarker - a gene product or other signal whose presence is an indication of a
- phenotype or activity
- oncogene - a gene known to be involved in causing cancer
- perturbagen - a substance (small molecule, shRNA, peptide, etc.) designed to disrupt
- intracellular processes
- master regulator - a gene for a transcription factor or signaling protein controlling the
- expression or repression of a number of direct target genes
- candidate master regulator - a master regulator identified in a computational screen
- but not yet confirmed in vitro
- interactor - a subject involved in an interaction network
- background - a subject necessary to understand the importance of the study but not
- part of that particular study
- candidate drug - a compound investigated as a potential new drug or for a new indication
- control compound - a compound used as control in an experiment
- metabolite - product of enzyme-catalyzed reaction
- disease - the condition or disease being investigated
- metastasis - spread of cancer cells to new areas of the body
- tissue - description of tissue used or investigated in an experiment
- cell line - a cell line used in an experiment
- strain - strain of an animal model

**Comment by kcs3** [comment]
Now we have to see where all to add the hover text:

- Role column entries on the Browse pages.
- Role column entries on the Observation Details pages.

**Comment by kcs3** [comment]
Tested in production v4.20.  Role definition hover-text is appearing as specified above.  The new definitions were added.
