### ISSUE TITLE
imperfect matching process of subjects in a submission

### ISSUE THREAD

**Issue by zhouji2013** [CBIIT/nci-ctd2-dashboard#426]
When a submission is loaded, the subjects are matched up with the background subject data. Roughly speaking, if an exact match of 'display name' is found, it is used; otherwise, an arbitrary 'less ideal' match is used. It is probably alright and even desirable for some subjects, but for gene symbols, this process is problematic, considering the different cases are used as the only mechanism to differentiate homo sapiens and mus musculus genes.

The detailed process for match gene symbol works this way: 

1. Try to find the 'main' symbol (not synonyms).
2. If no match is found in step 1, all genes that have a synonym that matches are found. This is case-insensitive.
3. Among all the genes found in steps 1 and 2, if there is one 'display name' (not synonyms) matching exactly, that is used.
4. If nothing is found in step 3, the first one (basically an arbitrary one)  from all the potential matches is used. 

Step 4 is where the result may not be right. For example, we have AKT1 for homo sapiens and Akt1 for mus musculus. If the symbol is entered as AKT, no exact match is found in step 3; then an arbitrary one from all the synonym+case-insensitive matches is used regardless of the species. So an intended homo sapiens gene might be linked to a mus musculus gene (this actually happened in the real data). Ideally, AKT should match AKT1 first and Akt should match Akt1 first,

**Comment by zhouji2013** [comment]
Based on Vlado's recommendation, the matching rules are further enhanced to allow only human genes to be matched by a synonym and mouse genes always be matched by a symbol only.

**Comment by zhouji2013** [comment]
After the last change, all the mismatched mouse genes appeared to be corrected. More genes are decided as "Cannot find" now, so I need to invesitiagte further before marking this issue as resolved.

**Comment by kcs3** [comment]
In an email dated 8/29/2019, Zhou identified 23 submissions containing 474 mouse gene symbols.  Vlado inspected the list and found that only the symbols from "20140124-ucsf-differential-expression" should actually have been mouse, the rest were human.

All those corrections were made.  I tested a number of the gene symbols in the original list and verified that they no longer hit mouse genes when searched on in the Dashboard, only human.
