### ISSUE TITLE
other pages spontaneously switch to the homepage with duplicated story links

### ISSUE THREAD

**Issue by zhouji2013** [CBIIT/nci-ctd2-dashboard#427]
When the homepage is first loaded, everything seems fine. But when you click a link to go to some other pages, e.g. "How to Cite" page, the display sometimes switches back to the homepage by itself, and the story links may start being re-created. This happens frequently but not very consistently over different browsers.

**Comment by kcs3** [comment]
Tested in production, version 3.3, on both Chrome and Firefox.  Problem is fixed.
