### ISSUE TITLE
do not show GeneCards links for mouse genes

### ISSUE THREAD

**Issue by zhouji2013** [CBIIT/nci-ctd2-dashboard#428]
GeneCards links should not be displayed on gene pages for mouse genes, like this one:
https://ctd2-dashboard.nci.nih.gov/dashboard/#gene/m/akt1

**Comment by zhouji2013** [comment]
xref loading procedure is modified so that mouse gene (different cases) will not linked to GeneCards

**Comment by kcs3** [comment]
Tested on local development version, GeneCards link does not display.

**Comment by kcs3** [comment]
The software change was included in release v3.40 but the change will not be visible until the next update of the data.  The data was not updated for release v3.40.

**Comment by kcs3** [comment]
For the given example linked above, verified that GeneCards link is not displayed on the gene subject page.
Closing issue.
