### ISSUE TITLE
API performance review and improvement

### ISSUE THREAD

**Issue by zhouji2013** [CBIIT/nci-ctd2-dashboard#429]
It was noticed that some of the API return time is much slower than expected.

Here are a few reported cases:
- https://ctd2-dashboard.nci.nih.gov/dashboard/api/submission/20150406-broad-cpd-sens-mutation-enrich about 3 minutes 10 seconds
- https://ctd2-dashboard.nci.nih.gov/dashboard/api/browse/gene/myc about 10 seconds
- https://ctd2-dashboard.nci.nih.gov/dashboard/api/search/myc about 15 seconds

Possible reasons of the less ideal performance: (1) the data model is designed to fit the original web app, and the queries are not optimized for the API (designed afterwards) either. (2) In the case of the first example above, the returned JSON object is very big (over 22 MB) so the size itself is a big factor in the returning time. We may want to reconsider whether such big queries are necessary or not, or we need to add new queries for better responding time, e.g. not including as much detail in a query for a submission as in this example.

**Comment by zhouji2013** [comment]
For reference, this is the ultimate official specification of API web/src/test/CTD2-Dashboard_API.yml

**Comment by kcs3** [comment]
I tried out the first example on the test server.  It seems to be continuing to deliver chunks of text every few seconds.  In the end it delivered at 21.3 MB file, but it took a minute or two to finish.  The second example finished essentially instantly.  The third example took maybe a second or two.

**Comment by zhouji2013** [comment]
> 
> 
> I tried out the first example on the test server. It seems to be continuing to deliver chunks of text every few seconds. In the end it delivered at 21.3 MB file, but it took a minute or two to finish. The second example finished essentially instantly. The third example took maybe a second or two.

The delay observed in the browser rendering is not an issue. The response (data in JSON format) is not meant to be used by the browser directly.

**Comment by kcs3** [comment]
Tested that JSON responses received as above in production release v4.20.
