### ISSUE TITLE
vulnerable submission page

### ISSUE THREAD

**Issue by zhouji2013** [CBIIT/nci-ctd2-dashboard#430]
One particular submission (20160919-tgen-eddy-ccle-ctrp) includes a large number of observations (22745). This is more than twice the number of the second largest observation number in one submission (8517 in 20150406-broad_cpd_sens_mutation_enrich). Such a large case was not safely implemented.

If you go to this URL
http://localhost:8080/dashboard/#submission/20160919-tgen-eddy-ccle-ctrp
then click on "To load all observations please click here". This will in fact freezes the front-end page, and possibly cause serious problem on the server-side app as well. I tested locally, but haven't tried it on the production site in case it causes unnecessary disruption for the public users.

The second largest number of observations can be tested at:
http://localhost:8080/dashboard/#submission/20150406-broad-cpd-sens-mutation-enrich

**Comment by zhouji2013** [comment]
some possible solutions:
1. disable the 'load all" feature if the number of observations is too big, say, over 1000. Instead, we can show a message reporting the number and that we cannot show the list. 
2. re-design how this page works both from the backbend and the frontend so we can have a reasonable responsiveness. This will introduce more complexity in the application and possibly have to comprises some features, e.g. the convenient filtering feature, which depends on the fact the whole table is in fact there in the browser.
3. remove or handle differently only the submission that has the exceptional big number of observations (22745). There are 8 other submissions with number of observations larger than 1000. We can either leave the system as is for them (it is still slow but not to the extent of crashing the app), or come up with some other improvement (which will be easier because the number is at most 8517).

Or some kind of combination of the three approaches?

**Comment by kcs3** [comment]
The text in the yellow highlight box for example #submission/20160919-tgen-eddy-ccle-ctrp
reads "Only 100 of 22745 observations are listed in the table below. To load all observations please click here (this might take a while)."

To make the system safe right now, let's first implement suggestion #1.  In the case that there are more than 1000 (or whatever is reasonable) observations, change the second sentence from "To load all observations please click here (this might take a while)."" to "There are too many observations to display in the browser; download the complete set of observations as a file."  With "download" being a hyperlink to the source data file (already available above in information area above it).

**Comment by kcs3** [comment]
I tested this on the submission with the most observations, #submission/20160919-tgen-eddy-ccle-ctrp

It works as advertised.  I downloaded the observation template file and all the rows are there.

Note for documentation that although this feature is triggered if there are more than 1000 observations, in that case it only displays the first 100, that is, the standard default number.

**Comment by kcs3** [comment]
Just to describe further the difference in behavior when this condition is triggered, in the normal case, e.g. there are 223 total observations, the user can click a link to display all 223 (https://ctd2-dashboard.nci.nih.gov/dashboard/#submission/20150406-broad-cpd-sens-lineage-enrich).  However, when there are more than 1000 total observations, the user cannot see say the first 1000 in the  browser, instead they must go ahead and download the CSV file to see anything over 100.  This is fine, doing otherwise would be needlessly complex.

Tested on production release v3.40.  Closing issue.
