### ISSUE TITLE
empty evidence code

### ISSUE THREAD

**Issue by kcs3** [CBIIT/nci-ctd2-dashboard#432]
In https://ctd2-dashboard.nci.nih.gov/dashboard/#observation/20190212-columbia-paracne-1-colony-0, there are five rows of "measured" evidence. The first four have ECO code http://www.evidenceontology.org/term/ECO:0000059/, but the 5th has no code at all.  

Is this a code problem, or is there some reason behind it?

**Comment by kcs3** [comment]
The four pieces of evidence with role "measured" that get an automatically assigned ECO code have evidence type "numeric".  The piece of evidence with role "measured" that does not get an automatically assigned ECO code has evidence type "label".

**Comment by kcs3** [comment]
Vlado, should we just add this to the list in your google sheet, as label, measured?  Does it make sense?

**Comment by kcs3** [comment]
Also, does the script catch and report combinations that are not entered into the sheet?

**Comment by kcs3** [comment]
Vlado suggests adding wildcard entry for unmatched entries

**Comment by vdancik** [comment]
Wildcard evidence codes consistent with the current codes:

evidence|role | eco_term | eco_id
:--: | -- | --|--
*|measured | direct assay evidence | ECO:0000002
*|observed | ad-hoc quantitative phenotype observation evidence | ECO:0005675
*|computed | computational combinatorial evidence | ECO:0000053
*|background | inference from background scientific knowledge | ECO:0000001
*|species | biological system reconstruction evidence by experimental evidence from single species | ECO:0005553
*|literature | traceable author statement | ECO:0000033
*|written | author statement | ECO:0000204
*|reference | traceable author statement | ECO:0000033
*|resource | imported information | ECO:0000311

**Comment by kcs3** [comment]
For the example given above, the default (wildcard) ECO code is being assigned as specified.

**Comment by kcs3** [comment]
Tested in production, closing issue.
