### ISSUE TITLE
Adding Evidence Ontology Support to the CTD2

### ISSUE THREAD

**Issue by zhouji2013** [CBIIT/nci-ctd2-dashboard#436]
We will develop infrastructure and guidance on how best to use assay-type codes from ECO. Codes from the Evidence Ontology (ECO) can be used to indicate the types of experimental methods used to generate submissions. For more details, see the attached specification document.
[Evidence Ontology Specification.docx](https://github.com/CBIIT/nci-ctd2-dashboard/files/3933135/Evidence.Ontology.Specification.docx)

**Comment by zhouji2013** [comment]
Per Aris's recommendation, the ECO code is expected to be entered as an additional field in *dashboard-CV-per-template.txt* file for each template (corresponding to each line in the file).

**Comment by zhouji2013** [comment]
[Evidence Ontology Design.docx](https://github.com/CBIIT/nci-ctd2-dashboard/files/4188216/Evidence.Ontology.Design.docx)

**Comment by zhouji2013** [comment]
I didn't link every relevant commit in this issue because the eco-codes branch is completely for this purpose https://github.com/CBIIT/nci-ctd2-dashboard/tree/eco-codes

**Comment by zhouji2013** [comment]
[dashboard-CV-per-template.txt](https://github.com/CBIIT/nci-ctd2-dashboard/files/4198717/dashboard-CV-per-template.txt)
Example file showing how ECO codes are added for three templates. The choice of the ECO codes and the templates in the example were made up completely arbitrarily.

**Comment by zhouji2013** [comment]
[dashboard-CV-per-template.txt](https://github.com/CBIIT/nci-ctd2-dashboard/files/4238484/dashboard-CV-per-template.txt)
An example file showing how multiple ECO codes are assigned to one template. They need to be delimited by "|", like "ECO:0007006|ECO:0000360", put at the end of the line in the per-template file, the same way as for a single ECO code.

**Comment by zhouji2013** [comment]
Some of the requirements described in the attached specification document belong to the template helper application, which is a separate repository. See https://github.com/CBIIT/nci-ctd2-dashboard-tmpl-helper/issues/53

**Comment by kcs3** [comment]
Updated version of template file.  Now has real ECO codes for 9 columbia submissions.  Removed the earlier demo codes.

[dashboard-CV-per-template.txt](https://github.com/CBIIT/nci-ctd2-dashboard/files/4283560/dashboard-CV-per-template.txt)

**Comment by kcs3** [comment]
Here is the latest revision of the  ECO term specification document. 

[EvidenceOntologySpecification.final.v2.docx](https://github.com/CBIIT/nci-ctd2-dashboard/files/4283972/EvidenceOntologySpecification.final.v2.docx)

**Comment by zhouji2013** [comment]
A newer version of the final edition: [EvidenceOntologySpecification.final.v3.docx](https://github.com/CBIIT/nci-ctd2-dashboard/files/4294000/EvidenceOntologySpecification.final.v3.docx)

**Comment by kcs3** [comment]
Note that a number of improvements to the handling ECO codes were specified in issue #442.

**Comment by kcs3** [comment]
The basic functionality as specified has been implemented, but still need a final item by item check.

**Comment by kcs3** [comment]
Under Experiment Annotation:
(1) Change "Please select one or more Evidence & Conclusion Ontology (ECO, http://www.evidenceontology.org/)" to Please select one or more [Evidence & Conclusion Ontology (ECO)](http://www.evidenceontology.org/) 

In the line below the checkbox list under Experiment Annotation, change the sentence as follows:

**It is strongly suggested that ECO terms from the list above be used**. However, if no term is appropriate for your submission, or additional terms are needed, please click here.

**Comment by zhouji2013** [comment]
item (3): the current behavior is more consistent with the assumption that nothing is saved until you click "Save" or "Save and Continue". If changed, the expectation that Summary change is not saved will become inconsistent unless we also change it; the Download button from Preview page will become different unless we change it as well; switching between 'pages' without saving will also be inconsistent if this Download button is clicked...

**Comment by zhouji2013** [comment]
item (4): this should not happen unless the *additional* term is in fact in the common term list, in which case they would be checked in the list instead of re-populated in the text box. Can you confirm the actual term that has the issue? Or do we want some logic more complicated, e.g. not allowing 'common term' to be entered in the text box, etc?

**Comment by kcs3** [comment]
Testing results:
For (1), only hyperlink the words "Evidence & Conclusion Ontology (ECO)".
(2) is good.  Maybe we could move out of passive voice later.
(3) pending further consideration.
(4) pending further investigation.
(5) is good.  Except how come it is not displaying the name for the valid code ECO:0001111?  Are we not loading the full ECO ontology?  If people can add their own terms, it seems like we will need this.

**Comment by kcs3** [comment]
Testing Evidence Terms against the specification document v3.  A few things to note:
1. There is no reset initial order button.  It does not seem necessary.
2. There is no hover-text e.g. on the Tier labels.  They should have the standard Tier definitions.  We need to write new hover text for "Name" and "Submissions".  (As a side note, when browsing Genes, I note that the hover text over "observations" is an empty bubble.
3.  I added a new issue #447 about a broken ECO term link.

**Comment by kcs3** [comment]
Issue #477 is fixed, so can close this issue now.  Will create a new issue regarding hover-text for "observations" on genes page as mentioned in (2) just above.
