### ISSUE TITLE
Change in font color to black

### ISSUE THREAD

**Issue by jagus7** [CBIIT/nci-ctd2-dashboard#439]
The grey font we have now on the Dashboard is blended with the background image of CTD^2 icon on the landing page. Hence, the font color should be changed from grey to black throughout the site.

**Comment by kcs3** [comment]
The text looks black to me already.  Changing the whole site for this one image may be excessive.  Maybe we can lighten the background image instead?

**Comment by kcs3** [comment]
Tested on test server.  Excellent, looks great.

**Comment by kcs3** [comment]
Tested on production server, looks good.
