### ISSUE TITLE
Changes requested during ECO code demo

### ISSUE THREAD

**Issue by kcs3** [CBIIT/nci-ctd2-dashboard#442]
1. On the home page, in the Dashboard Content Summary table, use proper display names, e.g. shRNA, Animal Model etc.
2. At the bottom of the Dashboard Content Summary table, let's just remove the word "Total" and leave it blank.
3. On the Evidence Terms browse page, the "Centers" numbers should show the count of unique centers.  That is, two "Columbia" entries for a term constitutes one center, not two.
4. On all browse pages, for entries that only have one center, add (1 center) to the table for visual consistency.
5. On the observation pages, under the heading Submission, at the end of the Description line in the table there is a link titled "details".    It links to the Submission page from which the observation originated.  Maybe can we remove the "details" link and just make the actual text of the Description a hyperlink to the submission instead.
6. When searching on two or more terms, the listing of the intersection of all terms is already mentioned in the ECO term specification document.  Actually implementing this may require further detailed planning.
7. Add space above and below the "Show/Hide Dashboard Content Summary".
8. On the homepage, add browse buttons in a second row for Stories, Cell Lines, and Experimental Evidence.

Other changes

9. We should add a note somewhere on the Experimental Evidence page that not all submissions have been annotated.  We can add this to the text already at the top of the page.  "Note - not all submissions have been annotated with Evidence Ontology codes"

10. Add examples for ECO codes, search by code e.g.  
** "Expt. Evidence Code: ECO_0006053"
** "Expt. Evidence term: PCR"

**Comment by zhouji2013** [comment]
The latest code has covered the first four items.

**Comment by zhouji2013** [comment]
Item 7: implemented in 3a60d3b.

**Comment by kcs3** [comment]
Verified that 1, 2, 3, 5, 7 and 8 have been implemented.
4 has not been implemented.
Have not tried 6 yet.
Verified that the two ECO term examples were added to the search menu hovertext.

Please separate the note "Note - not all submissions have been annotated with Evidence Ontology codes" from the preceeding text by a blank line to make it more visible as it is important to understanding the ECO terms table.

**Comment by zhouji2013** [comment]
Item 4 and the blank line after the note are implemented now.

**Comment by kcs3** [comment]
Verified everything above 1-10 implemented except 6, which requires additional specification.  We have discussed but needs more work.

**Comment by kcs3** [comment]
I have opened issue #443 to deal with point 6 above as it is a larger project. 

This issue can thus be called complete.

**Comment by kcs3** [comment]
Verified all items above in production release 4.0 except #6, which is now continued in its own issue, #443 for additional design and implementation.
Closing this issue.
