### ISSUE TITLE
Specification for Multi-Center submissions

### ISSUE THREAD

**Issue by kcs3** [CBIIT/nci-ctd2-dashboard#444]
[Multi-center submissions specification final.docx](https://github.com/CBIIT/nci-ctd2-dashboard/files/4429507/Multi-center.submissions.specification.final.docx)

The attached file includes Subhashinis's comments on the multi-center submission specification.  Where possible, the changes requested have been made in the document.

The one thing left to decide is how to indicate the CTD2 Center is pinned at the top of the Centers list.

**Comment by zhouji2013** [comment]
[dashboard-CV-per-template.txt](https://github.com/CBIIT/nci-ctd2-dashboard/files/4452208/dashboard-CV-per-template.txt)
This is an example file to test the new feature. It shows the follow changes (as fake test data) over a real data file:

1. One template has the center name "CTD² Network Collaboration".
2. The project name is appended with "(BR, CU)". This addition should be a list of the actual center abbreviations in real data.
3. Two templates have the center name "Other NCI Programs"
4. Each of the templates from "Other NCI Programs" has the project name ending with "(external center ....)", which should be the actual center names in real data.

**Comment by kcs3** [comment]
I think we decided to pin "CTD² Network Collaboration" at the top of the list, and "Other NCI Programs" at the bottom of the list. These two items will not be moved by sort operations, but all other Center entries will be.

**Comment by kcs3** [comment]
Note - this feature was not included in release v4.0

**Comment by kcs3** [comment]
Works as requested.  Looks good.

**Comment by kcs3** [comment]
Can't test in production until we actually get a joint-submission; I believe one is coming soon.  Will go ahead and close this issue.
