### ISSUE TITLE
Link out from Gene Cart to Enrichr

### ISSUE THREAD

**Issue by kcs3** [CBIIT/nci-ctd2-dashboard#449]
Add button to the Gene Cart to send a list of genes from the cart to the external Enrichr website, and trigger an automatic default analysis.  The result is displayed in the Enrichr website in a new page, not in the Dashboard.

**Comment by zhouji2013** [comment]
implemented in commits 2814f9aac and 1f3f21f4.

**Comment by kcs3** [comment]
Looks good.

**Comment by kcs3** [comment]
Tested in production, closing issue.
