### ISSUE TITLE
Harmonize mouse pointer appearance when hovering over clickable objects.

### ISSUE THREAD

**Issue by arisf** [CBIIT/nci-ctd2-dashboard#450]
At present, when hovering over something clickable, the mouse pointer sometimes turns into a hand cursor (e.g., when hovering over one of the buttons on the landing page) or a text select cursor (e.g., when hovering over the video links on the landing page). For consistency and usability, it would be preferable to always use the hand cursor.

**Comment by zhouji2013** [comment]
The links for the videos and the summary table were changed.

**Comment by kcs3** [comment]
I tested many pages including links and images and the hand always appears.  Looks good.

**Comment by kcs3** [comment]
Tested in production, closing issue.
