### ISSUE TITLE
Update DFCI Logo

### ISSUE THREAD

**Issue by jagus7** [CBIIT/nci-ctd2-dashboard#451]
DFCI has a new logo. Please update the existing Center logo with the new one. 

![image](https://user-images.githubusercontent.com/17437681/82361705-36872180-99d9-11ea-8991-06b50424f143.png)

**Comment by zhouji2013** [comment]
Should the left-side circular part be used as the 'small version' on the stories page https://ctd2-dashboard.nci.nih.gov/dashboard/#stories, or should this be used on the stories page as it is, or do they have an official small version?

**Comment by kcs3** [comment]
It looks nice but I notice that the background for this image is transparent, so that the words sort of get mixed up with the DNA graphic on submission pages.  There are a couple of others like this also, TGEN and CSHL.  Other images have white backgrounds.  I guess it is OK for now.

**Comment by kcs3** [comment]
I just noticed that the original image does seem to have a white background.  Can we make that visible?

**Comment by zhouji2013** [comment]
The real original image (provided during the working of this issue) has in fact a transparent background instead of a white one. The one attached here was likely not to be exported properly.

**Comment by kcs3** [comment]
Tested in production, closing issue.
