### ISSUE TITLE
Redesign Gene Cart gene list options

### ISSUE THREAD

**Issue by kcs3** [CBIIT/nci-ctd2-dashboard#453]
The gene-cart interface was originally designed under the assumption the CNKB would be the only consumer of the gene cart. We have now also added gene set enrichment. Additional functionality can be expected to be added here (e.g., querying the STRING database or/and other resources, preferably cancer-centric?) This should be re-examined by the group and cleaned-up if necessary before implementation.

Note for example that the descriptive text at the top specifically mentions the CNKB.

**Comment by kcs3** [comment]
[Redesign Gene Cart gene-list options.docx](https://github.com/CBIIT/nci-ctd2-dashboard/files/5176692/Redesign.Gene.Cart.gene-list.options.docx)

**Comment by arisf** [comment]
I suggest that the query options ("CNKB - Find Gene Interactions in Networks", "Enrichr - Gene Set Enrichment Analysis", "STRING - Protein-Protein Interaction Networks + Functional Enrichment Analysis") are instead added to a pick list (similar to what we currently use for selecting interactomes in the CNKB page, https://ctd2-dashboard.nci.nih.gov/dashboard/#cnkb-query), tied to a "Submit" button/link for initiating the querying action. Similar to the interactome functionality, selecting an option from the pick list can bring up a short, informative text below the pick list, explaining what the option allows the user to do.


"

**Comment by kcs3** [comment]
Updated version with Aris's suggestion:

[Redesign Gene Cart gene-list options.docx](https://github.com/CBIIT/nci-ctd2-dashboard/files/5190143/Redesign.Gene.Cart.gene-list.options.docx)

**Comment by kcs3** [comment]
Redesigned with Aris's comments
[Redesign Gene Cart gene-list options.docx](https://github.com/CBIIT/nci-ctd2-dashboard/files/5197415/Redesign.Gene.Cart.gene-list.options.docx)

**Comment by kcs3** [comment]
It works fine.  Could we maybe add just a tiny little bit of space between the "Select Action" box and the text beneath?

**Comment by kcs3** [comment]
New space between action box and text below looks good!

**Comment by kcs3** [comment]
Tested on production server, everything works fine.
