### ISSUE TITLE
incorrect search results

### ISSUE THREAD

**Issue by kcs3** [CBIIT/nci-ctd2-dashboard#457]
In testing the Dashboard with the three genes ACE2 TMPRSS2  CTSL, I found that when each gene symbol is searched individually, the only hit is for the searched gene itself.  However, when I search all three at once (no commas etc.), then 4 pages of results are returned, which comprise the three genes plus many ECO term hits.  

Also, if ACE2 TMPRSS2  is searched, or ACE2 CTSL, only those two genes are hit.  But if TMPRSS2  CTSL is searched, then all those extra ECO term hits are found.

This was tested in the production Dashboard.

**Comment by kcs3** [comment]
A second example is ACE2  NSC48300

**Comment by zhouji2013** [comment]
<img width="1008" alt="Screenshot 2020-06-02 15 04 40" src="https://user-images.githubusercontent.com/5490096/83559448-981fb380-a4e2-11ea-92e0-a359a9cafbdb.png">
I tested on the production, the testing instance, and the local development instance, and could not reproduce the problem. See the attached screenshot.

**Comment by kcs3** [comment]
I also  cannot repeat the result today, although I repeated it many times yesterday, for both positive and negative results.  I guess we will just have to keep an eye out for strange results.
