### ISSUE TITLE
Enhancement of Multi-term Search

### ISSUE THREAD

**Issue by kcs3** [CBIIT/nci-ctd2-dashboard#460]
The original proposal:

The Dashboard search box allows the user to enter one or more search terms. All Dashboard subjects containing any search word are returned. If there are multiple words in the search string, we attempt to identify whether the terms can be separated into a unique set of subjects that consume all of the searched words, and if so, we provide a list of observations from the intersection of all of the matched subjects (use of quotation marks around terms with multiple words in their name removes many inexact matches that thwart the exact matching required). In practical use, terms with long names will not be matched unless entered in quotation marks exactly as they appear in the subject name. In addition, the requirement for exact matching of term names prevents matching via synonyms or aliases. Examples:

- Searching on “ECO:0000229 TFAP4” (without quotes) correctly returns just the two terms and the 4 observations that contain both terms.

- The same results are also returned if all words from the ECO term title are used: “chromatin immunoprecipitation-seq evidence” TFAP4.
- Searching without quotes: chromatin immunoprecipitation-seq TFAP4 finds two CHiP-related terms plus TFAP4, but no observations because the word “evidence” was not included.

Therefore, we propose that where the search terms cannot be uniquely mapped to subject names, we will add the ability for the user to manually select which subjects to intersect. That is, of potentially many terms that may be returned by a general search, the user would select only the terms of interest. This could be realized by adding a checkbox beside each returned subject match and providing a button “Intersect selected”. Regarding the use of finding matches of child terms using subject ontologies, for search this would depend on which matching mode is in use. If children are rolled up into the parent term, then their observations would be included in any intersection involving the parent term. If child terms are shown separately, then they could be chosen for intersection using the manual method just described (GitHub issue #443 and in the ECO term specification document).

**Comment by zhouji2013** [comment]
As we discussed today, the following approach is to be used to decide the observation results: when the user enters "aaa bbb ccc", we will have all the observations that contains the subject results from "aaa", "bbb", "ccc", respectively, as thee sets. The final result should be the intersection of these three sets. In this process, "aaa bbb" does not need to be considered together unless they are entered quoted.

**Comment by kcs3** [comment]
Observations on testing:
Original example 1. searching on "ECO:0000229 TFAP4" returns the two subject terms as before, but not the four "Observations matching all search terms".
Original example 2. same result, we no longer see the four "Observations matching all search terms".
Original example 3. Now we get a lot more subjects hit than originally, but we do get the four "Observations matching all search terms".

**Comment by kcs3** [comment]
For a search on "immunoprecipitation-seq", 38 entries are returned, only one of which has that string in its name.  This is a good example to start with to understand how search is working now.

**Comment by kcs3** [comment]
After the fix above, search appears to be working as expected.  Here are a few test cases with results:

- **"chromatin immunoprecipitation-seq" TFAP4**  - returns the two subjects and four "Observations matching all search terms".
- **chromatin immunoprecipitation-seq TFAP4** (no quotes) - returns 25 subjects, two of which are ECO Terms with "chromatin" in their names, and the rest are genes.  Examined the first 5 genes, all had "chromatin" in their gene name or synonyms.  The same four "Observations matching all search terms" were returned.  These all had the ECO terms for "chromatin immunoprecipitation-seq" and TFAP4.

**Comment by kcs3** [comment]
We previously tried to match subject names to the largest number of search terms, and consume them before continuing to the next match.  We do not want to do that again.  However, we might make a few rules, such as:
1. look at the count of how many separate matched subject terms map to an observation.  If it is only 1, do not include it in  "Observations matching all search terms".  This is not a general solution, but will probably remove a lot of unwanted hits.  For example, for lung adenocarcinoma, "lung" and "adenocarcinoma" are both matching "lung adenocarcinoma" and that term should only be counted once.
2. The lack of "Observations matching all search terms" for ECO_0006053 EGLN1 means there is still some dependence on the search term rather than on the matched subject.

**Comment by kcs3** [comment]
Specification (draft) for results to display under "Observations matching all search terms".
- In the new implementation, for each unquoted word or quoted set of words, we find all observations matching each such term through a subject (or a subject's synonym?).
- In a second step, we find the intersection of observations that have matched all search words.

However, we have previously defined "Observations matching all search terms" to only be true if there is more than one matching subject.  That is, if two different words in the same search, like "lung" and "adenocarcinoma" both match the term "lung adenocarcinoma", we do not to count this as two matches, but as one.  We want to focus on interesting results, that is true intersections of at least two different terms.

This would seem to imply we need to keep track not only of observations matching each term, but which subjects matched each observation, and only display those observations that matched, in the simplest case, more than one different subject.  

So for example, if an observation contained just the subject "lung adenocarcinoma" it would not be matched by any combination of "lung" and "adenocarcinoma" for purposes of "Observations matching all search terms".  But if it contained both "lung" and "lung adenocarcinoma" as separate subjects, it should be displayed under "Observations matching all search terms".

**Comment by kcs3** [comment]
Verified fixed - searches with the terms "ECO_0006053 EGLN1" and "pharmacological assay EGLN1" (both without quotes), while producing different primary search results (since e.g. "assay" matches many ECO terms), both find the same "observation matching all search terms".

**Comment by kcs3** [comment]
A precise definition using set notation of the desired implementation of multiple term search is in the enhancements to search specification document, and the above description agrees closely with it, excluding the final step 4.  Any action on step 4 has been deferred to another time as we further explore the existing results in production and whether any further enhancements are actually called for.

**Comment by kcs3** [comment]
Just to summarize, searching for lung adenocarcinoma finds everything with lung, everything with adenocarcinoma, and everything with "lung adenocarcinoma" as a subject.  Under "Observations matching all search terms, there are 1391 entries.  The subject "Lung adenocarcinoma" accounts for 1371 of these.  See the above notes about why this result is different than with the previous implementation.  In short, although "lung adenocarcinoma" is one term, it is matching both search words and so now appears under "Observations matching all search terms.  Whether to implement suggestion 4 above which would remove these single subject hits is differed till another day.

Tested in production, closing issue.
