### ISSUE TITLE
Add NCI OCG logo to CTD2 pages

### ISSUE THREAD

**Issue by easaki** [CBIIT/nci-ctd2-dashboard#467]
NCI is trying to unify the look of their pages and has a long document for web site owners describing compliance. One of the requirements is to add an NCI logo to the top of NCI web sites. 

I suggest that we use a small strip at the top of each page with the NCI OCG logo such as https://ocg.cancer.gov

•	An authorized NCI logo. Only logos created by OCPL are authorized—if you need a logo, contact your DOC Communications Manager. The color version of your logo is preferred and must be used on a white background.

**Comment by kcs3** [comment]
![NCI-OCG logo](https://user-images.githubusercontent.com/5807704/89210545-481aa700-d58e-11ea-8f67-45bde5b0b198.png)

**Comment by kcs3** [comment]
![CTD2-NIH logo](https://user-images.githubusercontent.com/5807704/89210586-5f599480-d58e-11ea-9bd0-7781f647de24.png)

**Comment by zhouji2013** [comment]
@kcs3 Can you please confirm that we agree to add the top navigation bar (the entire dark blue part in Esther's screenshot above) to the dashboard? I assume this should show up on all pages.

**Comment by easaki** [comment]
Received message from NCI that the NCI footers may NOT be hidden. They must always be visible so they should not be in the section where we "hide" the attributions. They might need to be put in a stand alone section.

**Comment by easaki** [comment]
Also, the header mentioned above does not comply with the link-back to Resources for Researchers. We need a link that goes directly to: 
 https://www.cancer.gov/research/resources

I don't think we are REQUIRED to have that drop-down top section that goes back to the main NCI site. I think this is an option. However, Pam seemed to want to have it there. 

Still need to determine the best placement for the link to Resources for Researchers.

**Comment by kcs3** [comment]
OK as I understand it we will implement the full blue bar pulldown at the top of the site.  The link-outs that we put in the attribution section should now appear at all times, and they will be placed at the very bottom of the page, below the attributions section.  At some future time we will add the resources link.  There are many places it can now appear.

**Comment by easaki** [comment]
NCI website compliance group sent this code snippet for the "link-back" bar.
<script src="//assets.adobedtm.com/6a4249cd0a2c/0890c2def00a/launch-dbd676d3af6b.min.js" async></script>

**Comment by kcs3** [comment]
The NIH/NCI header and the links in the footer are in place in production release v4.20. The resources link is not yet in production, as it was just received (above).

**Comment by zhouji2013** [comment]
Everything we were supposed to do with this issue is done.

**Comment by kcs3** [comment]
We will only be able to see the final outcome on the NCI production server.

**Comment by kcs3** [comment]
Can't see results on production due to problems on the server-side, but our part in this is finished.  Closing issue.
