### ISSUE TITLE
Minor modifications to the CTD2 web sites - to comply with NCI standards

### ISSUE THREAD

**Issue by easaki** [CBIIT/nci-ctd2-dashboard#468]
NCI is trying to unify the look on its sites. Some minor modifications to the footer:
Change the various logos to text. We already have the required links (except USA.gov), but we need to change the images to text for:

•	The following text with links to the appropriate site: U.S. Department of Health and Human Services  |  National Institutes of Health  |  National Cancer Institute  |  USA.gov

**Comment by kcs3** [comment]
Esther please provide the desired links so we can implement this.

**Comment by kcs3** [comment]
<p class="rtecenter"><span class="policy"><a href="http://www.hhs.gov/" target="_blank">U.S. Department of Health and Human Services</a> / <a href="http://www.nih.gov" target="_blank">National Institutes of Health</a> / <a href="http://www.cancer.gov/" target="_blank">National Cancer Institute</a> / <a href="http://usa.gov" target="_blank">USA.gov</a></span></p>

**Comment by kcs3** [comment]
The header graphic and the attribution links are in place.  We are still waiting to hear details of a link out to NCI resources which will appear below the header graphic.

**Comment by kcs3** [comment]
Per #467 the links should now appear at all times, not in the attribution section.  Because #467 and #468 are now so intertwined, I'll mark #468 as complete and any further work should occur in #467.

**Comment by kcs3** [comment]
The NIH/NCI header and the links in the footer are in place in v4.20.  The resources link is not yet in production, see #467.
