### ISSUE TITLE
Make synonym listing collapsible

### ISSUE THREAD

**Issue by arisf** [CBIIT/nci-ctd2-dashboard#470]
Some subjects have very long lists of synonyms that cause undue scrolling when browsing search results and subject pages. E.g., see:
     https://ctd2-dashboard.nci.nih.gov/dashboard/#gene/h/hras
     https://ctd2-dashboard.nci.nih.gov/dashboard/#search/gene%2520expression%2520assay

Implement the following GUI change: In every page involving listing of synonyms for a subject, if there more than three synonyms associated with the subject, then:
1. List only the first three synonyms.
2. Include a collapsible toggle with two options "see all" (the default) and "hide" which can be used to show the full list of synonyms (the "see all" toggle) or revert back to the reduced listing of the first three synonyms (the "hide" toggle")

**Comment by kcs3** [comment]
As I understand it, this is per-page, not per subject.  This is the right way to go.  We might also want to remember the setting as the user pages through results.

**Comment by zhouji2013** [comment]
> 
> 
> As I understand it, this is per-page, not per subject. This is the right way to go. We might also want to remember the setting as the user pages through results.

It only makes sense to do this per subject. How can it work per page, the first three synonyms for the first subject, or the first synonym for three subjects, or something else?

**Comment by arisf** [comment]
Yes, the requirement is to be per subject.

**Comment by kcs3** [comment]
tested on test server, works fine.

**Comment by kcs3** [comment]
Tested on production server, works fine.
