### ISSUE TITLE
limit search return size on common synonym terms

### ISSUE THREAD

**Issue by kcs3** [CBIIT/nci-ctd2-dashboard#471]
In issue #240, we expanded the list of gene name synonyms that are searched. 

Some common words that appear in gene name synonyms are returning too many matches.  We may want to abandon a search that is matching too many terms and ask the user to provide a more specific search, either by e.g. 

1. supplying a more specific term or 
2. enclosing a more exact set of terms in quotation marks.

Examples of very common terms are gene, protein, and kinase

**Comment by kcs3** [comment]
Is there anything more to do on this?

**Comment by arisf** [comment]
Please note here the following possible situation:
* A search is run which returns a relatively small (i.e., fully displayable) number of hits (e.g., try searching using the following search terms (without quotes): Mature B-Cell Neoplasm
* That search is then expanded using the "Ontology Search" button, resulting in a large number of hits.

 At present, the rules for limiting display of hits does not appear to be in effect for the ontology search step. This needs to be rectified. As in the original search, if the ontology search returns a large number or hits, only a limited number should be displayed and the used should be advised to refine their search terms.

**Comment by arisf** [comment]
The solution to this issue is implemented following these requirements:
[handling_of_searches_returning_a_lot_hits.docx](https://github.com/CBIIT/nci-ctd2-dashboard/files/8051321/handling_of_searches_returning_a_lot_hits.docx)
.

**Comment by arisf** [comment]
Execute a search using the following search text (quotes included):
> "carcinom"

This will return a large number of results. However, the "Ontology Search" button remains active; per requirements, it should have been disabled.

**Comment by arisf** [comment]
Confirmed resolved on development server.

**Comment by arisf** [comment]
Verified on production server.
