### ISSUE TITLE
MRA view broken

### ISSUE THREAD

**Issue by zhouji2013** [CBIIT/nci-ctd2-dashboard#473]
The MRA view does not work any more. 

From an observation that contains MRA evidence, e.g. https://ctd2-dashboard.nci.nih.gov/dashboard/#observation/20130403-columbia-mra-fet-analysis-glioma-0, click "mra view" at the first evidence item. It goes to the MRA view at https://ctd2-dashboard.nci.nih.gov/dashboard/#mra/columbia-gbm-mra-networks-mra, but no content is displayed.

**Comment by zhouji2013** [comment]
The old code must have stopped working with some of library update, but it is not clear when this happened.

**Comment by kcs3** [comment]
Verfied fixed on test server.

**Comment by kcs3** [comment]
tested on production server, works fine now.

**Comment by kcs3** [comment]
closed
