### ISSUE TITLE
STRING DB query not working for the case of a single gene

### ISSUE THREAD

**Issue by zhouji2013** [CBIIT/nci-ctd2-dashboard#480]
STRING DB query from the gene cart works for multiple gene symbols, but shows "404 Not Found" for a single gene symbol. It seems caused by the STRING DB update.

**Comment by kcs3** [comment]
Tested on testing server.  Works for one or multiple genes now.

**Comment by kcs3** [comment]
Actually, for ENRICHR and STRING, now if there is more than one gene in the gene list, it only sends genes that are multiply-selected in the list.  By default this will just be one gene unless the user does a multiple selection.   The entire list of genes should always be sent to each service.

**Comment by kcs3** [comment]
Tested on production, works fine.  Note that, as expected, selecting one or more genes in the list sends only those genes to the service.  Default behavior is none selected.
