### ISSUE TITLE
URLs in CNKB interactome description not rendered correctly

### ISSUE THREAD

**Issue by zhouji2013** [CBIIT/nci-ctd2-dashboard#481]
Some of them miss 'http:' but still function. The ones for BIND are messed up and do not work nor look right.

**Comment by kcs3** [comment]
For the BIND description, the displayed URL (http://bind.ca) is no  longer valid.  In fact BIND was acquired by Clarivate and integrated into BOND.  For now, I suggest we just remove this URL "http://bind.ca" entirely, that is change it to (BIND), as in "The Biomolecular Interaction Network Database (BIND) is a"...

Also, the second URL does not point to the expected resource.  It should be removed entirely.

**Comment by zhouji2013** [comment]
> 
> 
> For the BIND description, the displayed URL (http://bind.ca) is no longer valid. In fact BIND was acquired by Clarivate and integrated into BOND. For now, I suggest we just remove this URL "http://bind.ca" entirely, that is change it to (BIND), as in "The Biomolecular Interaction Network Database (BIND) is a"...
> 
> Also, the second URL does not point to the expected resource. It should be removed entirely.

That is a CNKB data issue. Totally out of scope of CTD2.

**Comment by kcs3** [comment]
The problem actually addressed in this issue was not the content of the URLs, but that on the production site, the URL link included all text following the link.  This issue has been fixed.

**Comment by kcs3** [comment]
Tested on production, closing issue.
