### ISSUE TITLE
Adding DAP and Digital Tag Manager code to NCI websites

### ISSUE THREAD

**Issue by zhouji2013** [CBIIT/nci-ctd2-dashboard#483]
copied from the document forwarded in Pam's email on 2/20/2021:

The following tags must be added to all pages of the website:

    1. The first line of the <head> tag should be the following script tag: <script src="//assets.adobedtm.com/f1bfa9f7170c81b1a9a9ecdcc6c5215ee0b03c84/satelliteLib-4b219b82c4737db0e1797b6c511cf10c802c95cb.js"></script> 
    2. The last line of the body, just prior to the closing </body> tag, should be the following script tag: <script type="text/javascript">_satellite.pageBottom();</script>

**Comment by kcs3** [comment]
As noted in #467 we can't test this right now but all work is done on our side.  Closing issue.
