### ISSUE TITLE
“compounds and perturbagens” text on zoomed in landing page

### ISSUE THREAD

**Issue by birrielpc** [CBIIT/nci-ctd2-dashboard#484]
The “compounds and perturbagens” text should automatically adjust and stay within the rectangle when the page is zoomed in; may the CSS be updated on the Dashboard homepage to make sure the text wraps to a new line and the boxes increase in size?

![DB_compounds-and-pertubagens-text](https://user-images.githubusercontent.com/32900258/108762772-82459900-751e-11eb-9f4f-307fa1bd8593.PNG)

**Comment by kcs3** [comment]
This problem occurred not when the page was zoomed in on the browser, but when the browser window width was narrowed.  Within a certain range, the buttons would shrink with the page, but the text would not, until the text overflowed the buttons.  With this fix, the buttons add height to allow the text to wrap as the width decreases.
Tested OK on on test server.

**Comment by kcs3** [comment]
tested in production, closing issue.
