### ISSUE TITLE
Add word clouds

### ISSUE THREAD

**Issue by zhouji2013** [CBIIT/nci-ctd2-dashboard#485]
The specification is attached.
[CTD2 Dashboard wordcloud specification.pdf](https://github.com/CBIIT/nci-ctd2-dashboard/files/6373806/CTD2.Dashboard.wordcloud.specification.pdf)

**Comment by kcs3** [comment]
Implements #462.

**Comment by kcs3** [comment]
See also #492.  tested in production, closing issue.
