### ISSUE TITLE
Ontology-Enhanced Search

### ISSUE THREAD

**Issue by zhouji2013** [CBIIT/nci-ctd2-dashboard#487]
Attached is the requirement v8 (December 2, 2020).
[CTD2 Hierarchical search user level requirements draft - v8.docx](https://github.com/CBIIT/nci-ctd2-dashboard/files/6495258/CTD2.Hierarchical.search.user.level.requirements.draft.-.v8.docx)

**Comment by kcs3** [comment]
Need to add an hourglass-type busy indicator while ontology search is running.  The search is slow, and as search results are already displayed on the page, and because the ontology search results will be very similar to the original search results, it is impossible to tell if the new results have arrived.

**Comment by kcs3** [comment]
The original search example for this issue was "non-hodgkin" which is expected not  to return Burkitt's lymphoma when ontology search is not used, and to return Burkitt's lymphoma when ontology search is employed.  However, Burkitt's is not returned in either case.

**Comment by kcs3** [comment]
If in test I search on "non-hodgkin lymphoma" in quotes, it returns all 40 results that mention "lymphoma", seemingly ignoring the requirements of the quotes to match the entire term.  The production dashboard only returns one hit, for "follicular lymphoma", which has "non-hodgkin lymphoma" as a synonym.

**Comment by kcs3** [comment]
After an "ontology" search, the main search button still seems to be active (not greyed out), but it no longer launches a new regular search.  It seems like it should.

**Comment by kcs3** [comment]
Here are some test cases:
•	for disease context: search "organ", three results. "ontology search", 7 more results
•	for ECO: test case: search ECO_0000059 and you will get one result. If you do "ontology search", you will get three more results, which are children of ECO_0000059.
•	for observation: ECO_0000059 TP53. there is no direct 'intersection' but there will be intersection between child of ECO_0000059 (i.e. ECO_0000016) and TP53 so at least one observation result

I verified that each test case returned the results described, and that the results include new valid child nodes of the original search terms.

**Comment by kcs3** [comment]
It would be nice if we flagged the new results added by ontology search.  We could put a tiny little blue triangle in the upper-right corner of the Name field of the results page for ontology driven matches.

**Comment by kcs3** [comment]
Implements #459.

**Comment by zhouji2013** [comment]
> 
> 
> After an "ontology" search, the main search button still seems to be active (not greyed out), but it no longer launches a new regular search. It seems like it should.

I cannot reproduce this problem. Whether there is additional result or not, the button is disabled and greyed out. Did I misunderstand the description, or is the disabled color is not obvious enough? After the button is disabled, clicking the "Search" button (the original Search) will not re-activate it; you have to reload the page or navigate way to enable it again.

**Comment by kcs3** [comment]
> > After an "ontology" search, the main search button still seems to be active (not greyed out), but it no longer launches a new regular search. It seems like it should.
> 
> I cannot reproduce this problem. Whether there is additional result or not, the button is disabled and greyed out. Did I misunderstand the description, or is the disabled color is not obvious enough? After the button is disabled, clicking the "Search" button (the original Search) will not re-activate it; you have to reload the page or navigate way to enable it again.

I am speaking of the button labeled "search".  I do not see any visible difference in this button after an ontology search.  Also, is there some reason why it needs to be disabled at all?

**Comment by zhouji2013** [comment]
> 
> 
> > > After an "ontology" search, the main search button still seems to be active (not greyed out), but it no longer launches a new regular search. It seems like it should.
> > 
> > 
> > I cannot reproduce this problem. Whether there is additional result or not, the button is disabled and greyed out. Did I misunderstand the description, or is the disabled color is not obvious enough? After the button is disabled, clicking the "Search" button (the original Search) will not re-activate it; you have to reload the page or navigate way to enable it again.
> 
> I am speaking of the button labeled "search". I do not see any visible difference in this button after an ontology search. Also, is there some reason why it needs to be disabled at all?

I got it now. I misunderstood the original comment.

**Comment by zhouji2013** [comment]
Just to clarify the behavior of the main *Search* button. The button was never disabled. The confusion was caused by the design decision that ontology search is an interactive feature within the search page (with a stable URL) instead of being a different page. So the main *Search* button does not do anything because that is what it is supposed to do when the URL does not change. It is modified now to reload the page to eliminate the confusion. If a new search term is entered, *Search* button works as before and is not changed.

**Comment by zhouji2013** [comment]
Searching for "non-hodgkin" does not  find Burkitt's lymphoma because currently ontology search only starts with the exact 'unobserved' parent terms. For example, "mature B-cell non-Hodgkin's lymphoma" is a parent term of "Burkitt's lymphoma". Basic search for "mature B-cell non-Hodgkin's lymphoma"  (with quotes) does not return any result, but ontology search will return three results including "Burkitt's lymphoma".

**Comment by kcs3** [comment]
Tested on cloud instance.  
1. a "busy" indicator was added, 
2. a small blue triangle was added in the subject column to mark ontology search results,
3. a new search can be started from the search box after an ontology search.
4. searching on "non-hodgkin lymphoma" in quotes returns only a single result, as expected
4. no further action needed at this time on the "non-hodgkin's" ontology search.

**Comment by kcs3** [comment]
Tested in production.  Everything pretty much worked as expected.  Searching for "mature B-cell non-Hodgkin's lymphoma" in quotes in basic search does not seem finish, it just keeps searching....  Will enter as separate issue.  Suggest adding "busy" indicator to basic search just like we did for ontology search, will also add as new issue.

**Comment by kcs3** [comment]
This issue fully implemented requirements initially suggested in #265.
