### ISSUE TITLE
implement a demo application of Dashboard API

### ISSUE THREAD

**Issue by zhouji2013** [CBIIT/nci-ctd2-dashboard#489]
The specification as of Feb 8 is attached.
[molepro_user_interface_v4.docx](https://github.com/CBIIT/nci-ctd2-dashboard/files/8051599/molepro_user_interface_v4.docx)

**Comment by zhouji2013** [comment]
The app uses MolePro API. For details, see https://github.com/broadinstitute/molecular-data-provider

**Comment by kcs3** [comment]
For testing:
Just go to http://xxxx.xxx.xxx.xxx:xxxx/dashboard/api/ appending difference cases as following
browse/eco/eco-0000179 
browse/Evidence/eco-0000179
browse/Evidence/eco-0000229
browse/gene/myc
search/myc
search/eco-0000229
observation/20160425-dfci-cowley2014-ataris-analysis-867
observation/wrong-id
observations/20160919-tgen-eddy-ccle-ctrp/1,3-5,7,9-13
observations/20160919-tgen-eddy-ccle-ctrp/1,3-5,7,9-13-14

For example, http://xxxx.xxx.xxx.xxx:xxxx/dashboard/api/browse/eco/eco-0000179

**Comment by kcs3** [comment]
The API works fine for the examples above.

**Comment by kcs3** [comment]
I tried the queries listed, it all seems to work fine.  The "search/myc" query results in a number of genes returned, the first of which is BIN1.  I compared the returned values to those in the production Dashboard for BIN1.  Everything is them same except that whereas the Dashboard includes the UniProt ID, the API returns an Ensembl Id.  Both interfaces return the NCBI and gene cards ids.  So that is interesting.

**Comment by kcs3** [comment]
Further comparisons all look good.

**Comment by zhouji2013** [comment]
The changes to be make based on testing feedback:
1. when querying on gene, support both semicolon and comma as delimiters
2. in case there is no result for a given gene/compound, show the query term in the result with a message instead of showing nothing as it is now.

**Comment by zhouji2013** [comment]
The query of this app consists of two main steps. Step 1: find a list of compounds for a given gene (or find a list of genes for a given compound); Step 2: look up the detail of each compound (or gene) found in the Step 1. Step 1 is achieved with MolePro API as following for gene query:

1. use `'HGNC gene-list producer'` to get an ID for the given gene
2. query the ID obtained from the previous step on six transformers to get a list of IDs 
3. aggregate the list obtained from the previous step to get a URL
4. use the URL obtained from the previous step get a collection of names, which will be queried from CTD² API (main Step 2).

For compound query, the fist of the above 4 steps is a little different. API endpoint `/molecular_data_provider/compound/by_name/` is used instead of `transform`. The second step is different in that it uses 10 different transformers. Otherwise, it is the same as gene query.

**Comment by arisf** [comment]
Confirmed implemented per specifications in development server.
