### ISSUE TITLE
Adjust cytoscape viewer scale factor 

### ISSUE THREAD

**Issue by arisf** [CBIIT/nci-ctd2-dashboard#490]
The cytoscape viewer displays interaction networks retrieved from the CNKB. Right now, zooming in and out is very coarse, a single zoom in step greatly magnifies the network. Please adjust the scale factor (same as was done in the HIPC dashboard).

**Comment by zhouji2013** [comment]
1. see the HIPC dashboard solution for possible implication https://github.com/floratos-lab/hipc-signature/commit/eb444bdbf1c65db4cc13413e24b3d4e48e19ecda
2. cystoscope.js must be upgraded to 3.19 (from 3.3) to make this solution work

**Comment by kcs3** [comment]
Tested and compared with production version still running, the new zooming is better.

**Comment by kcs3** [comment]
tested in production, closing issue.
