### ISSUE TITLE
cBioPortal link not working

### ISSUE THREAD

**Issue by zhouji2013** [CBIIT/nci-ctd2-dashboard#491]
When the cBioPortal link (on gene page or cell sample page) is clicked, it opens a separate tab but has no content.

**Comment by zhouji2013** [comment]
After the fix, the new tab of cBioPortal is opened to the site. It looks fine for genes, but in the case of cell samples, it does not link to anything specific of that cell sample.

**Comment by kcs3** [comment]
I have gotten cBioportal results for both gene and cell line queries.  For example, cell line NCIH1299 does return a result.

https://www.cbioportal.org/patient?studyId=cellline_ccle_broad&sampleId=NCIH1299_LUNG

One of our most frequent cell lines, NCF10A does not have a result in cBioPortal which displays an error message:
https://www.cbioportal.org/patient?studyId=cellline_ccle_broad&sampleId=MCF10A_BREAST

In the future we might want to check our links against what is actually available on a site if they make this easily available.  But not in scope of this issue.

**Comment by kcs3** [comment]
tested in production, closing issue.
