### ISSUE TITLE
Word clouds: algorithm for abbreviating long terms

### ISSUE THREAD

**Issue by arisf** [CBIIT/nci-ctd2-dashboard#492]
See attached specification for new approach for abbreviating long terms.
[word_cloud_term_abbreviation_algorithm.docx](https://github.com/CBIIT/nci-ctd2-dashboard/files/6727180/word_cloud_term_abbreviation_algorithm.docx)

**Comment by kcs3** [comment]
When over a word, should the cursor change to indicate it is over a hyperlink?

**Comment by kcs3** [comment]
Looks like it correctly implements the spec.  Looks good.

**Comment by kcs3** [comment]
tested in production, closing issue
