### ISSUE TITLE
add Harmonizome URL to subject pages

### ISSUE THREAD

**Issue by zhouji2013** [CBIIT/nci-ctd2-dashboard#493]
The detail about the links in this document 
https://docs.google.com/spreadsheets/d/11sqRsA_pApnJeLyz34mJiDRIoExRXEIaDj63AAZe7lQ/edit#gid=0

**Comment by zhouji2013** [comment]
Only implemented for the gene page. It is not decided what to do with the protein page.

**Comment by kcs3** [comment]
Tested on test server, verified working.  Currently only implemented for genes.

**Comment by kcs3** [comment]
Verified working on production server.
