### ISSUE TITLE
API does not return UniProt ID for gene

### ISSUE THREAD

**Issue by kcs3** [CBIIT/nci-ctd2-dashboard#494]
On the gene page for BIN1,
https://ctd2-dashboard.nci.nih.gov/dashboard/#gene/h/bin1

under references, both the Ensembl and UniProt IDs are returned.  However, the API returns only the Ensemble ID:

https://ctd2-dashboard.nci.nih.gov/dashboard/api/browse/gene/bin1

This was seen during testing of #488.

Is this a bug?

**Comment by zhouji2013** [comment]
The discrepancy exists because although UniProt is displayed with other xref's, it is implemented differently.

**Comment by zhouji2013** [comment]
Vlado's recommendation:

> I would say that we should include UniProt to make API consistent with
web pages (even though it is implemented differently, to users it
appears as a regular cross-reference). Make "UniProt" a source and
whatever appears in a link would go to "id". For example in the ticket
it would look like this:

{
     "id":"O00499",
     "source": "UniProt"
}

**Comment by kcs3** [comment]
Verified fix on Columbia local test server.

**Comment by kcs3** [comment]
tested ok ion production server.
