### ISSUE TITLE
a link-out from CNKB result does not work

### ISSUE THREAD

**Issue by zhouji2013** [CBIIT/nci-ctd2-dashboard#498]
From Gene Cart (https://ctd2-dashboard.nci.nih.gov/dashboard/#genes), run a CNKB query, then click on 'Create network', then right-click a node in the network to see all the link-outs. The last one, 'CTD2-Dashboard', does not work. It is supposed to open the Search page for this term in a new tab.

**Comment by kcs3** [comment]
Verified fix on test server

**Comment by kcs3** [comment]
tested ok on production server.
