### ISSUE TITLE
wrong gene symbol is not warned when it is to be added to Gene Cart

### ISSUE THREAD

**Issue by zhouji2013** [CBIIT/nci-ctd2-dashboard#499]
Go to Gene Cart, click on "Add Gene", enter an incorrect gene symbol, e.g. XYZ, and click on "Submit". The dialog stays and no further response happens. An error message is supposed to pop up saying that "XYZ" is not a valid symbol.

**Comment by kcs3** [comment]
Verified fix on test.

**Comment by kcs3** [comment]
tested ok on production site.
