### ISSUE TITLE
Enhance the Cytoscape viewer to display additional information about the gene interactions

### ISSUE THREAD

**Issue by kcs3** [CBIIT/nci-ctd2-dashboard#501]
Improve user experience in interacting with the Cellular Network Knowledge Base (CNKB).  Enhance the functionality of the Cytoscape viewer to display additional information about the gene interactions retrieved from the CNKB, including likelihood, p-value, and mode of action

Requirements document:
[CNKB Improvements.docx](https://github.com/CBIIT/nci-ctd2-dashboard/files/9075612/github_.501_CNKB_improvements.docx)

**Comment by zhouji2013** [comment]
[CNKB Improvements_Ken 2-2-2022.docx](https://github.com/CBIIT/nci-ctd2-dashboard/files/8591391/CNKB.Improvements_Ken.2-2-2022.docx)
