### ISSUE TITLE
Visually flag additional results that were found by ontology search

### ISSUE THREAD

**Issue by zhouji2013** [CBIIT/nci-ctd2-dashboard#507]
Copied from "CTD22021-2022 Software Requirements":

This was initially specified in closed GitHub issue #487. It was later suggested that a more noticeable flag to indicate ontology results be provided, for example a blue rectangle with the word “onto” inside.
- Change the previously released blue triangle flag for the “onto” rectangle as shown in the figure below.
  - Be sure to provide enough additional space in the column to accommodate the box.
- When an ontology search has been performed, and new matches are found, add a legend describing the ontology flag: “Ontology search results flagged in Names column with onto”,as shown in the figure below. 
- If an ontology search finds no new matches, the legend should instead read “Ontology search found no additional terms”

**Comment by zhouji2013** [comment]
The current flagging solution (to be replaced by this one) is 4b022af

**Comment by kcs3** [comment]
tested on test server, works as expected.

**Comment by arisf** [comment]
tested on production server.
