### ISSUE TITLE
Add access to the Pathway Commons (PC) database

### ISSUE THREAD

**Issue by zhouji2013** [CBIIT/nci-ctd2-dashboard#510]
The contents of the Gene Cart will serve as input for two multi-gene queries against the Pathway Commons database: (1) a pathway search to retrieve pathways involving one or more of the query genes, and (2) an interactions search to display interactions involving the query genes. In both cases, results display will be directly on the Pathway Commons website, not on the Dashboard.

# Pathway search

Perform a multiple gene search (ACE2 TMPRSS2 CTSL TLR3 TLR7 TLR8 TLR9) with a URL of the form: https://apps.pathwaycommons.org/search?type=Pathway&q=ACE2%20TMPRSS2%20CTSL%20TLR3%20TLR7%20TLR8%20TLR9

The results page includes icons to display interactions, enrichment results, and a list of pathways with a choice of data source (default “Any datasource”).

# Interactions search

Display interactions involving multiple genes. E.g., for the genes in the previous example ((ACE2 TMPRSS2 CTSL TLR3 TLR7 TLR8 TLR9), the URL is: https://www.pathwaycommons.org/pcviz/#pathsbetween/ACE2,TMPRSS2,CTSL,TLR3,TLR7,TLR8,TLR9

Results are displayed in the form of an interactive network, using the PCViz visualizer.

# CTD2 Dashboard integration

The search options will appear within the “Select Action” area, under the “Gene Cart” -> “Go To Cart” menu option:

The new Pathway Commons options should be displayed using the following text:

- Pathway Commons - Data integrated from public pathway and interactions databases.

  - Pathway search: Find pathways

  - Interactions search: Display network of gene interactions

When the top-level entry is selected, the “Submit” button is disabled.

Add the following explanatory text to be displayed when an item above is selected:

- Pathway Commons: 
  - Pathway Commons collects and integrates data from public pathway and interactions databases. Pathway Commons is a collaboration between the Bader Lab at the University of Toronto, the Sander Lab at the Dana-Farber Cancer Institute and Harvard Medical School and the Demir Lab at Oregon Health & Science University.
- Pathway search:
  - Search Pathway Commons for pathways involving genes in the gene cart.
- Interaction viewer text:
  - Display and explore gene interaction network involving genes in the gene cart.

(text copied from CTD² 2021-2022 Software Requirements)

**Comment by arisf** [comment]
Confirmed one test server.

**Comment by arisf** [comment]
Verified on production server.
