### ISSUE TITLE
Unexpected search results

### ISSUE THREAD

**Issue by arisf** [CBIIT/nci-ctd2-dashboard#513]
When I search the Dashboard with the SINGLE search term below (quotes included):
> "cancer carcinoma"

I get back several subject matches. As far as I can see, none of those (including their synonyms) contain the text "cancer carcinoma". And in any case, if a subject matches that term, then (I would imagine) it should also match this one:
> "cancer car"

That second one returns zero hits.

**Comment by arisf** [comment]
Tested on development server.

**Comment by arisf** [comment]
Actually I still see some issues here. Specifically, when I search for
> blastoma

I only get back one hit, involving a gene. However, there are several tissue samples terms, associated with multiple observations, which contain the text "blastoma" in their name or/and synonyms (e.g., glioblastoma, neuroblastoma, etc.) . These should have been returned too.

**Comment by zhouji2013** [comment]
Basic search for "blastoma" does not return "glioblastoma" etc. because it does not match the whole word. Ontology search was implemented differently (using simple text match regardless of words) and has been modified to be the same as the basic search in 5ad599b9f6c33847e756c1decbadc1402481ba1b

**Comment by arisf** [comment]
When I search for the query term (quotes included):
> "tumor supressor"

I get no hits. I should at least have a hit for the TP53 gene, which includes this whole string in one of its synonyms (in fact, this same search in the production instance does return TP53).

**Comment by arisf** [comment]
All the issues reported above have been resolved satisfactorily. Results now match expected behavior under all different search scenarios tested.

**Comment by arisf** [comment]
Verified on production server.
