### ISSUE TITLE
Cross-referencing between compounds with shared protein targets

### ISSUE THREAD

**Issue by arisf** [CBIIT/nci-ctd2-dashboard#516]
While on the subject page for compound A, users should be able to identify and easily navigate to the subject pages for all compounds B sharing a common target with A.

See specific requirements: [Cross referencing related compounds.docx](https://github.com/CBIIT/nci-ctd2-dashboard/files/8825857/Cross.referencing.related.compounds.docx)

**Comment by zhouji2013** [comment]
The *compound relationship* that is to be presented in this feature is from the file called <code>CompoundAnnotations.txt</code>. This file has always been part of the 'background data' of CTD2 dashboard but is not actually used. Each line includes four fields: the first field is 'CPD_ID', which identifies the compound and the third field is 'ANNOTATION_ID', which identifies the target genes. All the compounds that are associated with a same target gene this way are those that should be crossed-reference in this feature.

**Comment by arisf** [comment]
Confirmed in production.
