### ISSUE TITLE
update the browse pages using new names of subject roles

### ISSUE THREAD

**Issue by zhouji2013** [CBIIT/nci-ctd2-dashboard#522]
The browser pages are organized based by subject roles. It needs to be modified using the new names of roles. The exact changes are specified in the attached spreadsheet.

Corresponding change also needs to be made in the template helper.

[dashboard-role-update-prop-v1.xlsx](https://github.com/CBIIT/nci-ctd2-dashboard/files/8920879/dashboard-role-update-prop-v1.xlsx)

**Comment by zhouji2013** [comment]
These two roles are consolidated as "regulator" so their tool-tip texts need to be consolidated as well.
-    'master regulator': 'a gene for a transcription factor or signaling protein controlling the expression or repression of a number of direct target genes',
-    'candidate master regulator': 'a master regulator identified in a computational screen but not yet confirmed in vitro',

**Comment by zhouji2013** [comment]
There is a new role, 'probe', It needs the tool-tip text similar to other roles.

**Comment by vdancik** [comment]
addressed by 331e3069f0572431e04dd5f83962a877c2832d53 and #526
